from __future__ import annotations

from .support import (
    ModelCatalog,
    Path,
    Profile,
    ProviderModelsResult,
    ProviderRegistry,
    StringIO,
    _discovered_model_entry,
    agent_config,
    cli_main,
    json,
    load_profile,
    os,
    patch,
    redirect_stdout,
    shutil,
    tempfile,
    unittest,
)


class ModelCatalogMutationTests(unittest.TestCase):
    def test_model_catalog_refresh_imports_provider_discovered_models(self) -> None:
        source = load_profile("local-dev", Path.cwd())
        models_config = json.loads(json.dumps(source.models))
        models_config.setdefault("models", {})["fixture-chat-small"] = {
            "provider": "ollama",
            "model": "provider-chat-small:8b",
            "enabled": True,
        }
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            profile = Profile(
                name="tmp",
                root=root,
                workspace=Path.cwd(),
                hardware=source.hardware,
                backends=source.backends,
                repository=source.repository,
                tools=source.tools,
                approvals=source.approvals,
                environment=source.environment,
                models=models_config,
                targets=source.targets,
            )
            discovered = ProviderModelsResult(
                provider="ollama",
                source="provider_api",
                models=[
                    "provider-chat-small:8b",
                    "new-embed-model:latest",
                    "new-coder:1b-base",
                ],
                reason="test discovery",
            )
            with patch.object(ProviderRegistry, "models", return_value=discovered):
                preview = ModelCatalog(profile).refresh("ollama", write=False, verbose=True)
                self.assertEqual(preview["changes"]["would_import"], 2)
                self.assertEqual(preview["results"]["ollama"]["source_models_returned"], 3)
                self.assertEqual(preview["results"]["ollama"]["source_models_already_profiled"], 1)
                self.assertEqual(preview["results"]["ollama"]["source_models_to_import"], 2)
                self.assertEqual(preview["changes"]["would_remove"], 0)
                self.assertNotIn("catalog", preview)
                rows = preview["results"]["ollama"]["model_changes"]
                imported_preview = {row["name"]: row for row in rows if row["refresh_status"] == "would_import"}
                self.assertEqual(
                    imported_preview["ollama-new-embed-model-latest"]["suitable_runtimes"],
                    ["ollama"],
                )
                self.assertEqual(
                    imported_preview["ollama-new-embed-model-latest"]["preferred_runtime"],
                    "ollama",
                )
                self.assertEqual(
                    imported_preview["ollama-new-embed-model-latest"]["ownership"],
                    "self_managed",
                )
                self.assertEqual(
                    imported_preview["ollama-new-embed-model-latest"]["local_presence"],
                    "pulled",
                )
                self.assertFalse((root / "models.yaml").exists())

                written = ModelCatalog(profile).refresh("ollama", write=True, verbose=True)

            self.assertEqual(written["changes"]["imported"], 2)
            self.assertEqual(written["changes"]["removed"], 0)
            self.assertTrue((root / "models.discovered.yaml").exists())
            if (root / "models.yaml").exists():
                self.assertIn(
                    "fixture-chat-small:",
                    (root / "models.yaml").read_text(encoding="utf-8"),
                )
            rows = written["results"]["ollama"]["model_changes"]
            names = {row["name"] for row in rows}
            self.assertIn("ollama-new-embed-model-latest", names)
            self.assertIn("ollama-new-coder-1b-base", names)
            discovered_text = (root / "models.discovered.yaml").read_text(encoding="utf-8")
            self.assertIn("This file is generated by aiplane model discovery", discovered_text)
            self.assertIn("Do not edit it manually", discovered_text)
            self.assertIn("enabled: true", discovered_text)

    def test_models_refresh_default_omits_provider_and_per_model_sections(self) -> None:
        discovered = ProviderModelsResult("ollama", "provider_api", ["new-model:1b"], "test discovery")
        with patch.object(ProviderRegistry, "models", return_value=discovered):
            stdout = StringIO()
            with redirect_stdout(stdout):
                code = cli_main(
                    [
                        "models",
                        "refresh",
                        "--profile",
                        "local-dev",
                        "--provider",
                        "ollama",
                        "--dry-run",
                    ]
                )
        self.assertEqual(code, 0)
        payload = json.loads(stdout.getvalue())
        self.assertEqual(payload["changes"]["would_import"], 1)
        self.assertNotIn("results", payload)
        self.assertNotIn("provider_summary", payload)
        self.assertEqual(payload["verbosity"], 0)

    def test_models_refresh_verbosity_one_adds_provider_summary(self) -> None:
        discovered = ProviderModelsResult("ollama", "provider_api", ["new-model:1b"], "test discovery")
        with patch.object(ProviderRegistry, "models", return_value=discovered):
            stdout = StringIO()
            with redirect_stdout(stdout):
                code = cli_main(
                    [
                        "models",
                        "refresh",
                        "--profile",
                        "local-dev",
                        "--provider",
                        "ollama",
                        "--dry-run",
                        "--verbosity",
                        "1",
                    ]
                )
        self.assertEqual(code, 0)
        payload = json.loads(stdout.getvalue())
        self.assertNotIn("results", payload)
        self.assertEqual(payload["verbosity"], 1)
        self.assertEqual(payload["provider_summary"][0]["provider"], "ollama")
        self.assertGreaterEqual(payload["provider_summary"][0]["model_changes_count"], 1)
        self.assertEqual(payload["provider_summary"][0]["changes"]["would_import"], 1)

    def test_models_refresh_cli_reports_configured_provider_failure_as_json(
        self,
    ) -> None:
        with patch.dict(os.environ, {"AZURE_OPENAI_ENDPOINT": "", "AZURE_OPENAI_API_KEY": ""}):
            stdout = StringIO()
            with redirect_stdout(stdout):
                code = cli_main(
                    [
                        "models",
                        "refresh",
                        "--profile",
                        "local-dev",
                        "--provider",
                        "azure_openai",
                        "--dry-run",
                        "--verbosity",
                        "1",
                    ]
                )
        self.assertEqual(code, 0)
        payload = json.loads(stdout.getvalue())
        self.assertEqual(payload["changes"]["would_import"], 0)
        summary = payload["provider_summary"][0]
        self.assertEqual(summary["provider"], "azure_openai")
        self.assertEqual(summary["status"], "failed")
        self.assertEqual(summary["source_contacted"], False)
        self.assertIn("endpoint_missing", summary["error"])
        self.assertEqual(
            summary["diagnostics"]["failure_codes"],
            ["endpoint_missing", "credential_missing"],
        )
        self.assertFalse(summary["diagnostics"]["network_contacted"])
        self.assertIn("providers show azure_openai", payload["next_steps"][0])

    def test_models_refresh_cli_previews_with_mocked_provider(self) -> None:
        discovered = ProviderModelsResult("ollama", "provider_api", ["new-model:1b"], "test discovery")
        with patch.object(ProviderRegistry, "models", return_value=discovered):
            stdout = StringIO()
            with redirect_stdout(stdout):
                code = cli_main(
                    [
                        "models",
                        "refresh",
                        "--profile",
                        "local-dev",
                        "--provider",
                        "ollama",
                        "--dry-run",
                        "--verbosity",
                        "2",
                    ]
                )
        self.assertEqual(code, 0)
        payload = json.loads(stdout.getvalue())
        self.assertEqual(payload["changes"]["would_import"], 1)
        self.assertNotIn("catalog", payload)
        rows = payload["results"]["ollama"]["model_changes"]
        imported = [row for row in rows if row["refresh_status"] == "would_import"]
        self.assertEqual(imported[0]["suitable_runtimes"], ["ollama"])
        self.assertEqual(imported[0]["ownership"], "self_managed")
        self.assertFalse(payload["write"])

    def test_models_refresh_cli_can_disable_new_imports_and_groups_provider_results(
        self,
    ) -> None:
        discovered = ProviderModelsResult("ollama", "provider_api", ["new-model:1b"], "test discovery")
        with patch.object(ProviderRegistry, "models", return_value=discovered):
            stdout = StringIO()
            with redirect_stdout(stdout):
                code = cli_main(
                    [
                        "models",
                        "refresh",
                        "--profile",
                        "local-dev",
                        "--provider",
                        "ollama",
                        "--disable-new",
                        "--dry-run",
                        "--verbosity",
                        "2",
                    ]
                )
        self.assertEqual(code, 0)
        payload = json.loads(stdout.getvalue())
        self.assertFalse(payload["write"])
        self.assertFalse(payload["new_entries_enabled"])
        imported = [
            row for row in payload["results"]["ollama"]["model_changes"] if row["refresh_status"] == "would_import"
        ]
        self.assertEqual(imported[0]["enabled"], False)

    def test_models_refresh_all_reports_mocked_provider_success_and_failure(
        self,
    ) -> None:
        source = load_profile("local-dev", Path.cwd())
        models_config = json.loads(json.dumps(source.models))
        models_config["models"] = {
            name: model
            for name, model in models_config["models"].items()
            if name in {"fixture-analysis-small", "provider-code-large-vllm"}
        }
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            profile = Profile(
                name="tmp",
                root=root,
                workspace=Path.cwd(),
                hardware=source.hardware,
                backends=source.backends,
                repository=source.repository,
                tools=source.tools,
                approvals=source.approvals,
                environment=source.environment,
                models=models_config,
                targets=source.targets,
                orchestrators=source.orchestrators,
            )

            def fake_models(provider: str, **kwargs) -> ProviderModelsResult:
                if provider == "ollama":
                    return ProviderModelsResult("ollama", "provider_api", ["fresh:1b"], "mock ok")
                if provider == "huggingface":
                    raise RuntimeError("mock failure")
                return ProviderModelsResult(provider, "profile_catalog", [], "empty")

            with patch.object(ProviderRegistry, "models", side_effect=fake_models):
                result = ModelCatalog(profile).refresh_all(write=False)
        self.assertGreaterEqual(result["providers_total"], 2)
        self.assertEqual(result["providers_failed"], 1)
        self.assertEqual(result["results"]["ollama"]["ownership"], "self_managed")
        self.assertEqual(result["results"]["ollama"]["status"], "would_update")
        self.assertEqual(result["results"]["huggingface"]["ownership"], "self_managed")
        self.assertEqual(result["results"]["huggingface"]["status"], "failed")
        self.assertNotIn("catalog", result)

    def test_models_refresh_all_still_uses_model_providers_after_catalog_clear(
        self,
    ) -> None:
        source = load_profile("local-dev", Path.cwd())
        models_config = json.loads(json.dumps(source.models))
        models_config["models"] = {"curated": {"provider": "ollama", "model": "curated:1b", "enabled": True}}
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            shutil.copytree(source.root, root / "local-dev")
            profile = load_profile("local-dev", Path.cwd(), profiles_dir=root)
            profile.models["models"] = models_config["models"]
            catalog = ModelCatalog(profile)
            catalog.clear_imported(write=False, include_curated=True)
            discovered = ProviderModelsResult("ollama", "source_api", ["fresh:1b"], "mock ok")

            def fake_models(provider: str, **kwargs) -> ProviderModelsResult:
                if provider == "ollama":
                    return discovered
                return ProviderModelsResult(provider, "profile_catalog", [], "empty")

            with patch.object(ProviderRegistry, "models", side_effect=fake_models):
                result = catalog.refresh_all(write=False)
        self.assertIn("ollama", result["results"])
        self.assertEqual(result["results"]["ollama"]["source_discovery_method"], "source_api")
        self.assertEqual(result["results"]["ollama"]["source_models_to_import"], 1)

    def test_models_enable_disable_rejects_discovered_cache_entry(self) -> None:
        source = load_profile("local-dev", Path.cwd())
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            models_config = {"models": {}}
            generated_config = {
                "models": {
                    "discovered_local": {
                        "provider": "ollama",
                        "source": "ollama",
                        "model": "llama3.2:3b",
                        "enabled": True,
                        "imported_by": "aiplane_refresh",
                    }
                }
            }
            (root / "models.yaml").write_text(agent_config.dump_yaml(models_config), encoding="utf-8")
            (root / "models.discovered.yaml").write_text(agent_config.dump_yaml(generated_config), encoding="utf-8")
            profile = Profile(
                name="tmp",
                root=root,
                workspace=Path.cwd(),
                hardware=source.hardware,
                backends=source.backends,
                repository=source.repository,
                tools=source.tools,
                approvals=source.approvals,
                environment=source.environment,
                models=models_config,
                targets=source.targets,
                orchestrators=source.orchestrators,
            )
            with self.assertRaisesRegex(ValueError, "discovered model entry is cache state"):
                ModelCatalog(profile).set_enabled("discovered_local", False)
            discovered_text = (root / "models.discovered.yaml").read_text(encoding="utf-8")
        self.assertIn("enabled: true", discovered_text)

    def test_models_refresh_reset_cache_previews_clear_before_refresh(self) -> None:
        source = load_profile("local-dev", Path.cwd())
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            profiles_dir = root / "profiles"
            shutil.copytree(source.root, profiles_dir / "local-dev")
            profile_root = profiles_dir / "local-dev"
            discovered_config = {
                "models": {
                    "ollama-old-model-latest": {
                        "provider": "ollama",
                        "source": "ollama",
                        "model": "old-model:latest",
                        "enabled": True,
                        "imported_by": "aiplane_refresh",
                    }
                }
            }
            (profile_root / "models.discovered.yaml").write_text(
                agent_config.dump_yaml(discovered_config),
                encoding="utf-8",
            )
            discovered = ProviderModelsResult("ollama", "provider_api", ["fresh:1b"], "mock ok")
            with patch.object(ProviderRegistry, "models", return_value=discovered):
                stdout = StringIO()
                with redirect_stdout(stdout):
                    code = cli_main(
                        [
                            "--profiles-dir",
                            str(profiles_dir),
                            "models",
                            "refresh",
                            "--profile",
                            "local-dev",
                            "--provider",
                            "ollama",
                            "--reset-cache",
                            "--dry-run",
                            "--verbosity",
                            "2",
                        ]
                    )
        self.assertEqual(code, 0)
        payload = json.loads(stdout.getvalue())
        self.assertEqual(payload["reset_cache"]["name"], "model_catalog_clear_cache")
        self.assertEqual(payload["reset_cache"]["provider"], "ollama")
        self.assertGreaterEqual(payload["reset_cache"]["would_remove"], 1)
        self.assertIn(
            {"name": "ollama", "count": payload["reset_cache"]["would_remove"]},
            payload["reset_cache"]["provider_counts"],
        )
        self.assertEqual(payload["changes"]["would_import"], 1)

    def test_model_catalog_clear_cache_removes_only_refresh_imports(self) -> None:
        source = load_profile("local-dev", Path.cwd())
        models_config = json.loads(json.dumps(source.models))
        models_config["models"] = {"curated": {"provider": "ollama", "model": "curated:1b", "enabled": True}}
        for index in range(55):
            models_config["models"][f"imported-{index:02d}"] = {
                "provider": "vllm",
                "source": "huggingface",
                "model": f"org/model-{index:02d}",
                "enabled": True,
                "imported_by": "aiplane_refresh",
            }
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / "models.yaml").write_text(agent_config.dump_yaml(models_config), encoding="utf-8")
            profile = Profile(
                name="tmp",
                root=root,
                workspace=Path.cwd(),
                hardware=source.hardware,
                backends=source.backends,
                repository=source.repository,
                tools=source.tools,
                approvals=source.approvals,
                environment=source.environment,
                models=models_config,
                targets=source.targets,
                orchestrators=source.orchestrators,
            )
            preview = ModelCatalog(profile).clear_imported(write=False)
            self.assertEqual(preview["would_remove"], 56)
            self.assertEqual(
                preview["provider_counts"],
                [{"name": "huggingface", "count": 55}, {"name": "ollama", "count": 1}],
            )
            self.assertEqual(preview["curated_provider_counts"], [{"name": "ollama", "count": 1}])
            self.assertTrue(preview["include_curated"])
            self.assertNotIn("model_changes", preview)

            keep_curated = ModelCatalog(profile).clear_imported(write=False, include_curated=False)
            self.assertEqual(keep_curated["would_remove"], 55)
            self.assertEqual(keep_curated["provider_counts"], [{"name": "huggingface", "count": 55}])
            self.assertEqual(keep_curated["curated_provider_counts"], [])
            self.assertFalse(keep_curated["include_curated"])

            written = ModelCatalog(profile).clear_imported(write=True, include_curated=False)
            self.assertEqual(written["removed"], 55)
            self.assertEqual(written["provider_counts"], [{"name": "huggingface", "count": 55}])
            self.assertEqual(written["curated_provider_counts"], [])
            written_text = (root / "models.yaml").read_text(encoding="utf-8")
            self.assertIn("curated:", written_text)
            self.assertNotIn("imported-00:", written_text)

    def test_discovered_huggingface_image_classifier_does_not_default_to_chat_roles(
        self,
    ) -> None:
        entry = _discovered_model_entry(
            "huggingface",
            "AdamCodd/vit-base-nsfw-detector",
            enable=True,
            source_metadata={"pipeline_tag": "image-classification"},
        )
        self.assertEqual(entry["roles"], ["image_classification"])
        self.assertNotIn("chat", entry["roles"])
        self.assertEqual(entry["preferred_runtime"], "vllm")

    def test_discovered_huggingface_media_pipeline_tags_map_to_media_roles(
        self,
    ) -> None:
        cases = [
            ({"pipeline_tag": "text-to-speech"}, "text_to_speech", "transformers", 0),
            ({"pipeline_tag": "text-to-image"}, "image_generation", "diffusers", 12),
            ({"pipeline_tag": "text-to-video"}, "video_generation", "diffusers", 8),
        ]
        for metadata, role, runtime, min_vram in cases:
            with self.subTest(role=role):
                entry = _discovered_model_entry("huggingface", f"org/{role}", enable=False, source_metadata=metadata)
                self.assertEqual(entry["roles"], [role])
                self.assertEqual(entry["source"], "huggingface")
                self.assertEqual(entry["provider"], runtime)
                self.assertEqual(entry["preferred_runtime"], runtime)
                if role == "image_generation" or role == "video_generation":
                    self.assertEqual(entry["supported_runtimes"], ["diffusers", "comfyui"])
                if role == "text_to_speech":
                    self.assertEqual(entry["supported_runtimes"], ["transformers"])
                self.assertEqual(entry["min_vram_gb"], min_vram)
                self.assertGreater(entry["capability_scores"][role], 0)
                self.assertFalse(entry["enabled"])

    def test_models_promote_generated_moves_alias_to_curated_catalog(self) -> None:
        source = load_profile("local-dev", Path.cwd())
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            models_config = {
                "providers": {"ollama": {"runtime": "ollama"}},
                "models": {},
            }
            generated_config = {
                "models": {
                    "generated-provider-chat": {
                        "provider": "ollama",
                        "model": "provider-text-small:0.5b",
                        "source": "ollama",
                        "roles": ["chat"],
                        "enabled": True,
                        "imported_by": "aiplane_refresh",
                    }
                }
            }
            (root / "models.yaml").write_text(agent_config.dump_yaml(models_config), encoding="utf-8")
            (root / "models.discovered.yaml").write_text(agent_config.dump_yaml(generated_config), encoding="utf-8")
            profile = Profile(
                "tmp",
                root,
                Path.cwd(),
                source.hardware,
                source.backends,
                source.repository,
                source.tools,
                source.approvals,
                source.environment,
                models_config,
                source.targets,
                source.orchestrators,
            )

            preview = ModelCatalog(profile).promote_generated(
                "generated-provider-chat",
                new_name="reviewed-provider-chat",
                write=False,
            )
            self.assertEqual(preview["would_promote"], 1)
            self.assertIn("next_steps", preview)
            self.assertIn("without --dry-run", preview["next_steps"][0])
            self.assertIn(
                "generated-provider-chat",
                (root / "models.discovered.yaml").read_text(encoding="utf-8"),
            )

            written = ModelCatalog(profile).promote_generated(
                "generated-provider-chat", new_name="reviewed-provider-chat", write=True
            )
            self.assertEqual(written["promoted"], 1)
            self.assertIn("next_steps", written)
            self.assertIn("models.yaml", written["next_steps"][0])
            curated_text = (root / "models.yaml").read_text(encoding="utf-8")
            generated_text = (root / "models.discovered.yaml").read_text(encoding="utf-8")
            self.assertIn("reviewed-provider-chat:", curated_text)
            self.assertIn("promoted_from: generated-provider-chat", curated_text)
            self.assertIn("discovered_entry: generated-provider-chat", curated_text)
            self.assertNotIn("imported_by", curated_text)
            self.assertIn("generated-provider-chat:", generated_text)

    def test_models_promote_refuses_curated_alias_collision_without_overwrite(
        self,
    ) -> None:
        source = load_profile("local-dev", Path.cwd())
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            models_config = {
                "providers": {"ollama": {"runtime": "ollama"}},
                "models": {
                    "generated-provider-chat": {
                        "provider": "ollama",
                        "model": "existing",
                        "source": "ollama",
                        "enabled": True,
                    }
                },
            }
            generated_config = {
                "models": {
                    "generated-provider-chat": {
                        "provider": "ollama",
                        "model": "provider-text-small:0.5b",
                        "source": "ollama",
                        "enabled": True,
                    }
                }
            }
            (root / "models.yaml").write_text(agent_config.dump_yaml(models_config), encoding="utf-8")
            (root / "models.discovered.yaml").write_text(agent_config.dump_yaml(generated_config), encoding="utf-8")
            profile = Profile(
                "tmp",
                root,
                Path.cwd(),
                source.hardware,
                source.backends,
                source.repository,
                source.tools,
                source.approvals,
                source.environment,
                models_config,
                source.targets,
                source.orchestrators,
            )

            with self.assertRaises(ValueError):
                ModelCatalog(profile).promote_generated("generated-provider-chat", write=False)

            preview = ModelCatalog(profile).promote_generated("generated-provider-chat", write=False, overwrite=True)
            self.assertTrue(preview["target_exists"])
            self.assertTrue(preview["overwrite"])

    def test_refresh_verbose_rows_use_model_source_and_runtime_endpoint_names(
        self,
    ) -> None:
        source = load_profile("local-dev", Path.cwd())
        models_config = json.loads(json.dumps(source.models))
        models_config["models"] = {
            "speech": {
                "provider": "transformers",
                "source": "huggingface",
                "model": "Provider/speech-to-text-large",
                "enabled": True,
                "preferred_runtime": "faster_whisper",
            }
        }
        profile = Profile(
            name="tmp",
            root=Path.cwd(),
            workspace=Path.cwd(),
            hardware=source.hardware,
            backends=source.backends,
            repository=source.repository,
            tools=source.tools,
            approvals=source.approvals,
            environment=source.environment,
            models=models_config,
            targets=source.targets,
            orchestrators=source.orchestrators,
        )
        discovered = ProviderModelsResult(
            "huggingface",
            "source_api",
            ["Provider/speech-to-text-large"],
            "live source",
            {"Provider/speech-to-text-large": {"downloads": 3}},
        )
        with patch.object(ProviderRegistry, "models", return_value=discovered):
            result = ModelCatalog(profile).refresh("huggingface", write=False, verbose=True)
        row = result["results"]["huggingface"]["model_changes"][0]
        self.assertNotIn("provider", row)
        self.assertEqual(
            row["model"],
            {"id": "Provider/speech-to-text-large", "source": "huggingface"},
        )
        self.assertEqual(row["runtime_endpoint"], "transformers")
        self.assertEqual(row["preferred_runtime"], "faster_whisper")
        self.assertIn("faster_whisper", row["suitable_runtimes"])

    def test_model_catalog_refresh_updates_source_metadata_and_preserves_curated_fields(
        self,
    ) -> None:
        source = load_profile("local-dev", Path.cwd())
        models_config = json.loads(json.dumps(source.models))
        models_config["models"] = {
            "curated-provider-chat": {
                "provider": "vllm",
                "source": "huggingface",
                "model": "Provider/Code-Large-Instruct",
                "enabled": True,
                "roles": ["manual_role"],
                "notes": "keep this note",
                "preferred_runtime": "transformers",
                "capability_scores": {"code_generation": 5, "debugging_refactor": 4},
                "capability_score_source": "manual",
                "source_metadata": {"downloads": 1},
            }
        }
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / "models.yaml").write_text(agent_config.dump_yaml(models_config), encoding="utf-8")
            profile = Profile(
                name="tmp",
                root=root,
                workspace=Path.cwd(),
                hardware=source.hardware,
                backends=source.backends,
                repository=source.repository,
                tools=source.tools,
                approvals=source.approvals,
                environment=source.environment,
                models=models_config,
                targets=source.targets,
                orchestrators=source.orchestrators,
            )
            discovered = ProviderModelsResult(
                "huggingface",
                "source_api",
                ["Provider/Code-Large-Instruct"],
                "live source",
                {
                    "Provider/Code-Large-Instruct": {
                        "downloads": 99,
                        "pipeline_tag": "text-generation",
                    }
                },
            )
            with patch.object(ProviderRegistry, "models", return_value=discovered):
                preview = ModelCatalog(profile).refresh("huggingface", write=False, verbose=True)
                self.assertEqual(preview["changes"]["would_update"], 1)
                self.assertIn("next_steps", preview)
                self.assertIn(
                    "aiplane models refresh --provider huggingface",
                    preview["next_steps"][0],
                )
                self.assertEqual(preview["results"]["huggingface"]["source_models_to_update"], 1)
                self.assertEqual(
                    preview["results"]["huggingface"]["profile_curated_models_before_refresh"],
                    1,
                )
                self.assertEqual(
                    preview["results"]["huggingface"]["profile_refresh_imported_models_before_refresh"],
                    0,
                )
                written = ModelCatalog(profile).refresh("huggingface", write=True, verbose=True)

            self.assertEqual(written["changes"]["updated"], 1)
            model = profile.models["models"]["curated-provider-chat"]
            self.assertEqual(
                model["source_metadata"],
                {"downloads": 99, "pipeline_tag": "text-generation"},
            )
            self.assertEqual(model["roles"], ["manual_role"])
            self.assertEqual(model["notes"], "keep this note")
            self.assertEqual(model["preferred_runtime"], "transformers")
            self.assertEqual(model["capability_score_source"], "manual")
            self.assertEqual(model["capability_scores"]["code_generation"], 5)

    def test_model_catalog_refresh_updates_refresh_imported_fields_from_source(
        self,
    ) -> None:
        source = load_profile("local-dev", Path.cwd())
        models_config = json.loads(json.dumps(source.models))
        models_config["models"] = {
            "hf-old": {
                "provider": "vllm",
                "source": "huggingface",
                "model": "org/old-embed",
                "enabled": True,
                "roles": ["chat"],
                "imported_by": "aiplane_refresh",
                "source_metadata": {"downloads": 1},
            }
        }
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            profile = Profile(
                name="tmp",
                root=root,
                workspace=Path.cwd(),
                hardware=source.hardware,
                backends=source.backends,
                repository=source.repository,
                tools=source.tools,
                approvals=source.approvals,
                environment=source.environment,
                models=models_config,
                targets=source.targets,
                orchestrators=source.orchestrators,
            )
            discovered = ProviderModelsResult(
                "huggingface",
                "source_api",
                ["org/old-embed"],
                "live source",
                {"org/old-embed": {"downloads": 2}},
            )
            with patch.object(ProviderRegistry, "models", return_value=discovered):
                written = ModelCatalog(profile).refresh("huggingface", write=True, verbose=True)
            self.assertEqual(written["changes"]["updated"], 1)
            generated_models = ModelCatalog(profile).generated_config["models"]
            self.assertEqual(generated_models["hf-old"]["roles"], ["embedding"])
            self.assertEqual(generated_models["hf-old"]["source_metadata"], {"downloads": 2})

    def test_model_catalog_refresh_prunes_live_discovery_but_not_fallback(self) -> None:
        source = load_profile("local-dev", Path.cwd())
        models_config = json.loads(json.dumps(source.models))
        models_config.setdefault("models", {})["fixture-chat-small"] = {
            "provider": "ollama",
            "model": "provider-chat-small:8b",
            "enabled": True,
        }
        models_config.setdefault("models", {})["fixture-analysis-small"] = {
            "provider": "ollama",
            "model": "provider-text-small:0.5b",
            "enabled": True,
        }
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / "models.yaml").write_text(agent_config.dump_yaml(models_config), encoding="utf-8")
            profile = Profile(
                name="tmp",
                root=root,
                workspace=Path.cwd(),
                hardware=source.hardware,
                backends=source.backends,
                repository=source.repository,
                tools=source.tools,
                approvals=source.approvals,
                environment=source.environment,
                models=models_config,
                targets=source.targets,
                orchestrators=source.orchestrators,
            )
            live = ProviderModelsResult(
                "ollama",
                "provider_api",
                ["provider-chat-small:8b"],
                "live runtime inventory",
            )
            with patch.object(ProviderRegistry, "models", return_value=live):
                preview = ModelCatalog(profile).refresh("ollama", write=False, verbose=True)
                self.assertEqual(preview["changes"]["would_remove"], 0)
                self.assertTrue(preview["results"]["ollama"]["prune_enabled"])
                self.assertIn(
                    "fixture-analysis-small:",
                    (root / "models.yaml").read_text(encoding="utf-8"),
                )

                written = ModelCatalog(profile).refresh("ollama", write=True, verbose=True)

            self.assertEqual(written["changes"]["removed"], 0)
            written_text = (root / "models.yaml").read_text(encoding="utf-8")
            self.assertIn("fixture-analysis-small:", written_text)
            self.assertIn("fixture-chat-small:", written_text)

            fallback_profile = Profile(
                name="tmp",
                root=root,
                workspace=Path.cwd(),
                hardware=source.hardware,
                backends=source.backends,
                repository=source.repository,
                tools=source.tools,
                approvals=source.approvals,
                environment=source.environment,
                models=json.loads(json.dumps(models_config)),
                targets=source.targets,
                orchestrators=source.orchestrators,
            )
            fallback = ProviderModelsResult(
                "ollama",
                "profile_catalog",
                ["provider-chat-small:8b"],
                "offline fallback",
            )
            with patch.object(ProviderRegistry, "models", return_value=fallback):
                fallback_result = ModelCatalog(fallback_profile).refresh("ollama", write=True)
            self.assertFalse(fallback_result["results"]["ollama"]["prune_enabled"])
            self.assertEqual(fallback_result["changes"]["removed"], 0)
