from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

from .boundaries import CommandRunner, HttpTransport, SubprocessCommandRunner, UrllibHttpTransport
from .backends import (
    BackendResult,
)
from .model_refresh import ModelRefreshCoordinator
from .model_store import ModelCatalogStore
from .models import Profile
from .model_resources import (
    accelerator_api_requirements as _accelerator_api_requirements,
    gpu_vendor_requirement as _gpu_vendor_requirement,
    matches_accelerator_api_requirement as _matches_accelerator_api_requirement,
    matches_gpu_vendor_requirement as _matches_gpu_vendor_requirement,
    number_or_none as _number_or_none,
    parameter_billions as _parameter_billions,
    resource_estimate_source as _resource_estimate_source,
    resource_guess as _resource_guess,
    size_bonus as _size_bonus,
)


DISCOVERED_MODELS_FILE = "models.discovered.yaml"
DISCOVERED_MODELS_BANNER = (
    "# This file is generated by aiplane model discovery.\n"
    "# Do not edit it manually; use `aiplane models refresh`, `aiplane models add`, or `aiplane models promote`.\n"
    "# Promote/add reviewed entries into models.yaml for durable profile configuration.\n"
)


@dataclass(frozen=True)
class ModelStatus:
    name: str
    provider: str
    configured: bool
    usable: bool
    reason: str


class ModelCatalog:
    def __init__(
        self,
        profile: Profile,
        command_runner: CommandRunner | None = None,
        http_transport: HttpTransport | None = None,
    ):
        self.profile = profile
        self.command_runner = command_runner or SubprocessCommandRunner()
        self.http_transport = http_transport or UrllibHttpTransport()
        self.config = profile.models or {}
        self.store = ModelCatalogStore(profile.root, DISCOVERED_MODELS_FILE, DISCOVERED_MODELS_BANNER)
        self.generated_config = self.store.load_generated()

    def providers(self) -> dict[str, dict[str, Any]]:
        from .runtime_catalog import PROVIDER_ENDPOINT_DEFAULTS

        providers = {name: dict(value) for name, value in PROVIDER_ENDPOINT_DEFAULTS.items()}
        for name, value in _dict_of_dicts(self.config.get("providers", {})).items():
            providers[name] = {**providers.get(name, {}), **value, "origin": "profile"}
        return providers

    def models(self) -> dict[str, dict[str, Any]]:
        generated = _dict_of_dicts(self.generated_config.get("models", {}))
        curated = _dict_of_dicts(self.config.get("models", {}))
        return {**generated, **curated}

    def defaults(self) -> dict[str, Any]:
        defaults = self.config.get("defaults", {})
        return defaults if isinstance(defaults, dict) else {}

    def default_model(self, role: str, require_enabled: bool = True) -> dict[str, Any] | None:
        name = self.defaults().get(role)
        models = self.models()
        if not name or str(name) not in models:
            return None
        model = models[str(name)]
        if require_enabled and not bool(model.get("enabled", True)):
            return None
        return {"role": role, "name": str(name), "model": model}

    def default_summary(self) -> dict[str, Any]:
        rows = []
        models = self.models()
        for role, name in self.defaults().items():
            model = models.get(str(name))
            rows.append(
                {
                    "role": role,
                    "name": name,
                    "exists": isinstance(model, dict),
                    "enabled": (bool(model.get("enabled", True)) if isinstance(model, dict) else False),
                    "provider": (model.get("provider") if isinstance(model, dict) else None),
                    "model": model.get("model") if isinstance(model, dict) else None,
                }
            )
        return {"defaults": rows}

    def set_default(self, role: str, name: str) -> dict[str, Any]:
        if not role or "/" in role or "\\" in role:
            raise ValueError("default role must be a simple name")
        model = self.get(name)
        self.config.setdefault("defaults", {})[role] = name
        path = self.store.write_curated(self.config)
        return {
            "role": role,
            "name": name,
            "provider": model.get("provider"),
            "model": model.get("model"),
            "path": str(path),
        }

    def add_model(
        self,
        name: str,
        provider: str | None = None,
        model_id: str | None = None,
        discovered_name: str | None = None,
        roles: list[str] | None = None,
        supported_runtimes: list[str] | None = None,
        preferred_runtime: str | None = None,
        enabled: bool = True,
        notes: str | None = None,
        settings: dict[str, Any] | None = None,
        write: bool = True,
        overwrite: bool = False,
    ) -> dict[str, Any]:
        _validate_model_entry_name(name, "model entry name")
        direct_local_file = provider == "local_file" and model_id and not discovered_name
        curated_models = _dict_of_dicts(self.config.get("models", {}))
        generated_models = _dict_of_dicts(self.generated_config.get("models", {}))
        target_exists = name in curated_models
        if direct_local_file:
            discovered_key = None
            generated_name_collision = name in generated_models
            if (target_exists or generated_name_collision) and not overwrite:
                raise ValueError(
                    f"model entry already exists: {name}; use --overwrite after reviewing the existing entry"
                )
            entry = self._build_local_file_entry(
                model_id=str(model_id),
                roles=roles,
                supported_runtimes=supported_runtimes,
                preferred_runtime=preferred_runtime,
                enabled=enabled,
                notes=notes,
                settings=settings,
            )
        else:
            discovered_key, discovered_entry = self._resolve_discovered_entry(
                provider=provider,
                model_id=model_id,
                discovered_name=discovered_name,
            )
            generated_name_collision = name in generated_models and name != discovered_key
            if (target_exists or generated_name_collision) and not overwrite:
                raise ValueError(
                    f"model entry already exists: {name}; use --overwrite after reviewing the existing entry"
                )

            entry = self._build_model_entry(
                provider=provider,
                model_id=model_id,
                discovered_name=discovered_key,
                discovered_entry=discovered_entry,
                roles=roles,
                supported_runtimes=supported_runtimes,
                preferred_runtime=preferred_runtime,
                enabled=enabled,
                notes=notes,
                settings=settings,
            )
        if write:
            curated_models[name] = entry
            self.config["models"] = curated_models
            self._write_curated_config()
        return {
            "name": "model_catalog_add",
            "entry": name,
            "discovered_entry": discovered_key,
            "write": write,
            "overwrite": overwrite,
            "target_exists": target_exists,
            "added": 1 if write else 0,
            "would_add": 0 if write else 1,
            "path": str(self.profile.root / "models.yaml"),
            "discovered_path": str(self._generated_path()),
            "model": entry,
            "next_steps": _model_entry_next_steps(name, write),
        }

    def _build_local_file_entry(
        self,
        model_id: str,
        roles: list[str] | None,
        supported_runtimes: list[str] | None,
        preferred_runtime: str | None,
        enabled: bool,
        notes: str | None,
        settings: dict[str, Any] | None,
    ) -> dict[str, Any]:
        entry: dict[str, Any] = {
            "provider": "local_file",
            "source": "local_file",
            "model": model_id,
            "local": True,
            "ownership": "self_managed",
            "enabled": bool(enabled),
            "curated": True,
            "roles": _string_list(roles or []),
        }
        if supported_runtimes:
            entry["supported_runtimes"] = _string_list(supported_runtimes)
        if preferred_runtime:
            entry["preferred_runtime"] = preferred_runtime
        elif supported_runtimes and len(supported_runtimes) == 1:
            entry["preferred_runtime"] = str(supported_runtimes[0])
        if notes is not None:
            entry["notes"] = notes
        for key, value in (settings or {}).items():
            entry[str(key)] = value
        return entry

    def clone_model(
        self,
        source_name: str,
        target_name: str,
        roles: list[str] | None = None,
        supported_runtimes: list[str] | None = None,
        preferred_runtime: str | None = None,
        enabled: bool | None = None,
        notes: str | None = None,
        settings: dict[str, Any] | None = None,
        write: bool = True,
        overwrite: bool = False,
    ) -> dict[str, Any]:
        _validate_model_entry_name(source_name, "source model entry name")
        _validate_model_entry_name(target_name, "target model entry name")
        source = dict(self.get(source_name))
        curated_models = _dict_of_dicts(self.config.get("models", {}))
        generated_models = _dict_of_dicts(self.generated_config.get("models", {}))
        target_exists = target_name in curated_models
        if (target_exists or target_name in generated_models) and not overwrite:
            raise ValueError(
                f"model entry already exists: {target_name}; use --overwrite after reviewing the existing entry"
            )
        entry = dict(source)
        entry.pop("imported_by", None)
        entry.pop("promoted_from", None)
        entry["cloned_from"] = source_name
        entry["curated"] = True
        if roles is not None:
            entry["roles"] = _string_list(roles)
        if supported_runtimes is not None:
            entry["supported_runtimes"] = _string_list(supported_runtimes)
        if preferred_runtime:
            entry["preferred_runtime"] = preferred_runtime
        if enabled is not None:
            entry["enabled"] = bool(enabled)
        if notes is not None:
            entry["notes"] = notes
        for key, value in (settings or {}).items():
            entry[str(key)] = value
        if write:
            curated_models[target_name] = entry
            self.config["models"] = curated_models
            self._write_curated_config()
        return {
            "name": "model_catalog_clone",
            "source": source_name,
            "target": target_name,
            "write": write,
            "overwrite": overwrite,
            "target_exists": target_exists,
            "cloned": 1 if write else 0,
            "would_clone": 0 if write else 1,
            "path": str(self.profile.root / "models.yaml"),
            "model": entry,
            "next_steps": _model_entry_next_steps(target_name, write),
        }

    def _build_model_entry(
        self,
        provider: str | None,
        model_id: str | None,
        discovered_name: str,
        discovered_entry: dict[str, Any],
        roles: list[str] | None,
        supported_runtimes: list[str] | None,
        preferred_runtime: str | None,
        enabled: bool,
        notes: str | None,
        settings: dict[str, Any] | None,
    ) -> dict[str, Any]:
        entry: dict[str, Any] = dict(discovered_entry)
        entry.pop("imported_by", None)
        entry.pop("promoted_from", None)
        entry["discovered_entry"] = discovered_name
        entry["enabled"] = bool(enabled)
        entry["curated"] = True
        if provider and "source" not in entry:
            entry["source"] = provider
        if model_id:
            entry["model"] = model_id
        if roles:
            entry["roles"] = _string_list(roles)
        elif "roles" not in entry:
            entry["roles"] = []
        if supported_runtimes:
            entry["supported_runtimes"] = _string_list(supported_runtimes)
        if preferred_runtime:
            entry["preferred_runtime"] = preferred_runtime
        if notes is not None:
            entry["notes"] = notes
        for key, value in (settings or {}).items():
            entry[str(key)] = value
        return entry

    def _resolve_discovered_entry(
        self,
        provider: str | None = None,
        model_id: str | None = None,
        discovered_name: str | None = None,
    ) -> tuple[str, dict[str, Any]]:
        generated_models = _dict_of_dicts(self.generated_config.get("models", {}))
        if discovered_name:
            _validate_model_entry_name(discovered_name, "discovered model entry name")
            entry = generated_models.get(discovered_name)
            if not entry:
                raise ValueError(f"discovered model entry not found: {discovered_name}")
            if provider and model_source(entry) != provider:
                raise ValueError(
                    f"discovered model entry {discovered_name} has source {model_source(entry)!r}, not {provider!r}"
                )
            if model_id and str(entry.get("model") or "") != model_id:
                raise ValueError(
                    f"discovered model entry {discovered_name} has model {entry.get('model')!r}, not {model_id!r}"
                )
            return discovered_name, dict(entry)
        if not provider:
            raise ValueError("provider is required unless --alias is used")
        if not model_id:
            raise ValueError("model id is required unless --alias is used")
        providers = self.providers()
        if provider not in providers:
            raise ValueError(f"unknown provider: {provider}")
        matches = [
            (name, entry)
            for name, entry in generated_models.items()
            if model_source(entry) == provider and str(entry.get("model") or "") == model_id
        ]
        if not matches:
            raise ValueError(
                f"discovered model entry not found for provider {provider!r} and model {model_id!r}; run models refresh first or use an existing discovered entry"
            )
        if len(matches) > 1:
            names = ", ".join(name for name, _entry in matches)
            raise ValueError(f"multiple discovered entries match provider/model; use --alias. Matches: {names}")
        name, entry = matches[0]
        return name, dict(entry)

    def _write_curated_config(self) -> Path:
        return self.store.write_curated(self.config)

    def list(self) -> list[dict[str, Any]]:
        rows = []
        from .runtime_catalog import RuntimeCatalog

        runtime_catalog = RuntimeCatalog(self.profile)
        from .benchmarks import latest_benchmark_summary

        for name, model in self.models().items():
            serving_provider = str(model.get("provider") or "")
            provider = self.providers().get(serving_provider, {})
            source_provider = model_source(model)
            capabilities = capability_profile(model)

            latest_benchmark = latest_benchmark_summary(self.profile, name)
            supported_runtimes = runtime_catalog.compatible_runtimes_for_entry(model, include_gui=True)
            ownership = ownership_for_model(model, provider)
            runtime_endpoint = None if ownership == "managed_service" else serving_provider
            configured_runtime_endpoints = [runtime for runtime in supported_runtimes if runtime in self.providers()]
            runtime_value = (
                None
                if ownership == "managed_service"
                else (model.get("preferred_runtime") or provider.get("runtime") or runtime_endpoint)
            )
            source_metadata = model.get("source_metadata") if isinstance(model.get("source_metadata"), dict) else {}
            rows.append(
                {
                    "name": name,
                    "provider": source_provider,
                    "source": source_provider,
                    "model": model.get("model"),
                    "parameter_count_b": _parameter_billions(str(model.get("model") or "")),
                    "capability_avg_score": _capability_average(capabilities),
                    "latest_benchmark": latest_benchmark,
                    "ownership": ownership,
                    "runtime": runtime_value,
                    "supported_runtimes": supported_runtimes,
                    "runtime_endpoint": runtime_endpoint,
                    "configured_runtime_endpoints": configured_runtime_endpoints,
                    "roles": model.get("roles", []),
                    "enabled": bool(model.get("enabled", True)),
                    "min_ram_gb": _number_or_none(model.get("min_ram_gb")),
                    "recommended_ram_gb": _number_or_none(model.get("recommended_ram_gb")),
                    "min_vram_gb": _number_or_none(model.get("min_vram_gb")),
                    "recommended_vram_gb": _number_or_none(model.get("recommended_vram_gb")),
                    "resource_estimate_source": _resource_estimate_source(model),
                    "gpu_vendor_requirement": _gpu_vendor_requirement(model),
                    "accelerator_api_requirements": _accelerator_api_requirements(model),
                    "likes": _metadata_number(source_metadata, "likes"),
                    "downloads": _metadata_number(source_metadata, "downloads"),
                    "source_metadata": source_metadata,
                    "capability_tags": capability_tags(capabilities),
                    "top_capabilities": top_capabilities(capabilities),
                    "capabilities": capabilities,
                }
            )
        return sorted(rows, key=lambda row: row["name"])

    def filter(self, filters: dict[str, Any]) -> list[dict[str, Any]]:
        rows = self.list()
        capability_filters = filters.get("capabilities") or {}
        result = []
        from .runtime_catalog import RuntimeCatalog

        runtime_catalog = RuntimeCatalog(self.profile)
        for row in rows:
            model = self.get(str(row["name"]))
            if filters.get("provider") and row.get("provider") != filters["provider"]:
                continue
            if filters.get("source") and row.get("source") != filters["source"]:
                continue
            if filters.get("runtime") and filters["runtime"] not in runtime_catalog.supported_runtimes(
                str(row["name"])
            ):
                continue
            roles_filter = _string_list(filters.get("roles") or filters.get("role"))
            if roles_filter and not any(role in row.get("roles", []) for role in roles_filter):
                continue
            if filters.get("enabled_only") and not row.get("enabled"):
                continue
            if filters.get("ownership") and row.get("ownership") != filters["ownership"]:
                continue
            score_source = filters.get("score_source")
            if score_source and row.get("capabilities", {}).get("score_source") != score_source:
                continue
            min_capability_avg = filters.get("min_capability_avg_score")
            if min_capability_avg is not None and float(row.get("capability_avg_score", 0)) < float(min_capability_avg):
                continue
            benchmark = row.get("latest_benchmark") if isinstance(row.get("latest_benchmark"), dict) else None
            min_benchmark = filters.get("min_benchmark_score")
            if min_benchmark is not None:
                if not benchmark or float(benchmark.get("average_score", 0)) < float(min_benchmark):
                    continue
            if filters.get("require_benchmark") and not benchmark:
                continue
            min_likes = filters.get("min_likes")
            if min_likes is not None and float(row.get("likes") or 0) < float(min_likes):
                continue
            min_downloads = filters.get("min_downloads")
            if min_downloads is not None and float(row.get("downloads") or 0) < float(min_downloads):
                continue
            scores = row["capabilities"]["scores"]
            if any(int(scores.get(name, 0)) < minimum for name, minimum in capability_filters.items()):
                continue
            min_ram = filters.get("max_min_ram_gb")
            if (
                min_ram is not None
                and _number_or_none(model.get("min_ram_gb"))
                and _number_or_none(model.get("min_ram_gb")) > float(min_ram)
            ):
                continue
            min_vram = filters.get("max_min_vram_gb")
            if (
                min_vram is not None
                and _number_or_none(model.get("min_vram_gb"))
                and _number_or_none(model.get("min_vram_gb")) > float(min_vram)
            ):
                continue
            min_parameters = filters.get("min_parameters_b")
            parameters = _parameter_billions(str(model.get("model") or ""))
            if min_parameters is not None and parameters < float(min_parameters):
                continue
            max_parameters = filters.get("max_parameters_b")
            if max_parameters is not None and (parameters <= 0 or parameters > float(max_parameters)):
                continue
            gpu_vendor = filters.get("gpu_vendor")
            if gpu_vendor and not _matches_gpu_vendor_requirement(model, str(gpu_vendor)):
                continue
            accelerator_api = filters.get("accelerator_api")
            if accelerator_api and not _matches_accelerator_api_requirement(model, str(accelerator_api)):
                continue
            result.append(row)
        return sorted(result, key=lambda row: str(row["name"]))

    def sort_rows(
        self,
        rows: list[dict[str, Any]],
        sort_by: str = "name",
        roles: list[str] | None = None,
    ) -> list[dict[str, Any]]:
        roles = _string_list(roles)
        sort_by = sort_by or "name"
        ranked_rows = (
            [_recommendation_row(row, roles) for row in rows]
            if roles or sort_by == "role"
            else [dict(row) for row in rows]
        )
        if sort_by == "name":
            return sorted(ranked_rows, key=lambda row: str(row.get("name", "")))
        if sort_by == "avg":
            return sorted(
                ranked_rows,
                key=lambda row: (
                    -float(row.get("capability_avg_score", 0)),
                    str(row.get("name", "")),
                ),
            )
        if sort_by == "benchmark":
            return sorted(
                ranked_rows,
                key=lambda row: (
                    -_benchmark_score(row),
                    -float(row.get("capability_avg_score", 0)),
                    str(row.get("name", "")),
                ),
            )
        if sort_by == "likes":
            return sorted(
                ranked_rows,
                key=lambda row: (
                    -float(row.get("likes") or 0),
                    -float(row.get("capability_avg_score", 0)),
                    str(row.get("name", "")),
                ),
            )
        if sort_by == "downloads":
            return sorted(
                ranked_rows,
                key=lambda row: (
                    -float(row.get("downloads") or 0),
                    -float(row.get("capability_avg_score", 0)),
                    str(row.get("name", "")),
                ),
            )
        if sort_by == "popularity":
            return sorted(
                ranked_rows,
                key=lambda row: (
                    -float(row.get("likes") or 0),
                    -float(row.get("downloads") or 0),
                    -float(row.get("capability_avg_score", 0)),
                    str(row.get("name", "")),
                ),
            )
        if sort_by == "parameters":
            return sorted(
                ranked_rows,
                key=lambda row: (
                    -float(row.get("parameter_count_b") or 0),
                    -float(row.get("capability_avg_score", 0)),
                    str(row.get("name", "")),
                ),
            )
        if sort_by == "role":
            if roles:
                return sorted(
                    ranked_rows,
                    key=lambda row: (
                        -float(row.get("role_score", 0)),
                        -float(row.get("capability_avg_score", 0)),
                        str(row.get("name", "")),
                    ),
                )
            return sorted(
                ranked_rows,
                key=lambda row: (
                    -float(row.get("capability_avg_score", 0)),
                    str(row.get("name", "")),
                ),
            )
        raise ValueError(f"unknown model sort: {sort_by}")

    def set_enabled(self, name: str, enabled: bool) -> dict[str, Any]:
        curated = _dict_of_dicts(self.config.get("models", {}))
        generated = _dict_of_dicts(self.generated_config.get("models", {}))
        if name in curated:
            curated[name]["enabled"] = bool(enabled)
            self.config["models"] = curated
            path = self.store.write_curated(self.config)
            return {"name": name, "enabled": bool(enabled), "path": str(path)}
        if name in generated:
            raise ValueError(
                f"discovered model entry is cache state, not profile-owned configuration: {name}; "
                "use models add first, or refresh/clear-cache to manage discovery cache"
            )
        raise ValueError(f"unknown profile-owned model: {name}")

    def refresh(
        self,
        provider_name: str = "ollama",
        write: bool = False,
        enable: bool = True,
        online: bool = True,
        query: str | None = None,
        limit: int = 500,
        progress: Callable[[str, str, str], None] | None = None,
        verbose: bool = False,
    ) -> dict[str, Any]:
        from .providers import ProviderRegistry

        registry = ProviderRegistry(self.profile)
        configured_providers = registry.model_providers()
        if provider_name not in configured_providers:
            raise ValueError(f"unknown catalog provider: {provider_name}")
        if progress:
            progress("connecting", provider_name, "")
        try:
            discovered = registry.models(provider_name, query=query, limit=limit, online=online)
        except Exception as exc:  # noqa: BLE001 - refresh should report configured provider failures as data.
            if progress:
                progress("failed", provider_name, str(exc))
            return self._refresh_failure_result(
                provider_name,
                write=write,
                enable=enable,
                online=online,
                query=query,
                limit=limit,
                verbose=verbose,
                error=str(exc),
                provider_config={
                    **configured_providers.get(provider_name, {}),
                    **self.providers().get(provider_name, {}),
                },
            )
        if discovered.source == "error":
            if progress:
                progress("failed", provider_name, discovered.reason)
            return self._refresh_failure_result(
                provider_name,
                write=write,
                enable=enable,
                online=online,
                query=query,
                limit=limit,
                verbose=verbose,
                error=discovered.reason,
                provider_config={
                    **configured_providers.get(provider_name, {}),
                    **self.providers().get(provider_name, {}),
                },
            )
        if progress:
            progress("succeeded", provider_name, f"{len(discovered.models)} source model(s)")
        return ModelRefreshCoordinator().run(
            self,
            discovered,
            provider_name,
            write=write,
            enable=enable,
            online=online,
            query=query,
            limit=limit,
            verbose=verbose,
        )

    def _refresh_failure_result(
        self,
        provider_name: str,
        *,
        write: bool,
        enable: bool,
        online: bool,
        query: str | None,
        limit: int,
        verbose: bool,
        error: str,
        provider_config: dict[str, Any],
    ) -> dict[str, Any]:
        all_models = self.models()
        provider_models = [model for model in all_models.values() if model_source(model) == provider_name]
        provider_imported_models = [model for model in provider_models if _is_refresh_imported_model(model)]
        provider_curated_models = [model for model in provider_models if not _is_refresh_imported_model(model)]
        changes = {
            "imported": 0,
            "would_import": 0,
            "updated": 0,
            "would_update": 0,
            "removed": 0,
            "would_remove": 0,
        }
        provider_result = {
            "ownership": str(
                provider_config.get("ownership")
                or (
                    "managed_service"
                    if provider_name in {"openai", "anthropic", "azure_openai", "ollama_cloud"}
                    else "self_managed"
                )
            ),
            "status": "failed",
            "source_contacted": False,
            "prune_enabled": False,
            "source_discovery_method": "error",
            "source_discovery_reason": error,
            "source_models_returned": 0,
            "profile_models_before_refresh": len(provider_models),
            "profile_curated_models_before_refresh": len(provider_curated_models),
            "profile_refresh_imported_models_before_refresh": len(provider_imported_models),
            "source_models_already_profiled": 0,
            "source_models_to_import": 0,
            "source_models_to_update": 0,
            "model_changes_count": 0,
            "changes": changes,
            "error": error,
        }
        path = self.profile.root / "models.yaml"
        discovered_path = self._generated_path()
        return {
            "name": "model_catalog_refresh",
            "write": write,
            "new_entries_enabled": enable,
            "online": online,
            "query": query,
            "limit": limit,
            "verbose": verbose,
            "path": str(path),
            "discovered_path": str(discovered_path),
            "changes": changes,
            "results": {provider_name: provider_result},
            "next_steps": _refresh_failure_next_steps(provider_name),
        }

    def refresh_all(
        self,
        write: bool = True,
        enable: bool = True,
        include_empty_providers: bool = False,
        online: bool = True,
        query: str | None = None,
        limit: int = 500,
        provider_limits: dict[str, int] | None = None,
        progress: Callable[[str, str, str], None] | None = None,
        verbose: bool = False,
    ) -> dict[str, Any]:
        from .providers import ProviderRegistry

        provider_rows = ProviderRegistry(self.profile).list(include_empty=True)
        results: dict[str, Any] = {}
        skipped_providers = []
        for provider_row in provider_rows:
            provider_name = str(provider_row["name"])
            if provider_name == "local_file":
                continue
            if provider_row.get("enabled") is False:
                skipped_providers.append(
                    {
                        "name": provider_name,
                        "reason": "model provider is disabled",
                        "typical_runtimes": provider_row.get("typical_runtimes", []),
                        "source_contacted": False,
                    }
                )
                continue
            try:
                provider_limit = int((provider_limits or {}).get(provider_name, limit))
                result = self.refresh(
                    provider_name,
                    write=write,
                    enable=enable,
                    online=online,
                    query=query,
                    limit=provider_limit,
                    progress=progress,
                    verbose=verbose,
                )
                provider_result = result.get("results", {}).get(provider_name, {})
                results[provider_name] = provider_result
            except Exception as exc:  # noqa: BLE001 - all-provider refresh should report provider-specific failures.
                results[provider_name] = {
                    "ownership": "self_managed",
                    "status": "failed",
                    "write": write,
                    "new_entries_enabled": enable,
                    "source_contacted": False,
                    "prune_enabled": False,
                    "source_discovery_method": "error",
                    "source_discovery_reason": str(exc),
                    "source_models_returned": 0,
                    "profile_models_before_refresh": len(
                        [model for model in self.models().values() if model_source(model) == provider_name]
                    ),
                    "profile_curated_models_before_refresh": len(
                        [
                            model
                            for model in self.models().values()
                            if model_source(model) == provider_name and not _is_refresh_imported_model(model)
                        ]
                    ),
                    "profile_refresh_imported_models_before_refresh": len(
                        [
                            model
                            for model in self.models().values()
                            if model_source(model) == provider_name and _is_refresh_imported_model(model)
                        ]
                    ),
                    "source_models_already_profiled": 0,
                    "source_models_to_import": 0,
                    "source_models_to_update": 0,
                    "changes": {
                        "imported": 0,
                        "would_import": 0,
                        "updated": 0,
                        "would_update": 0,
                        "removed": 0,
                        "would_remove": 0,
                    },
                    "model_changes_count": 0,
                    "error": str(exc),
                }
        rows = list(results.values())
        changes = {
            "imported": sum(int(row.get("changes", {}).get("imported", 0)) for row in rows),
            "would_import": sum(int(row.get("changes", {}).get("would_import", 0)) for row in rows),
            "updated": sum(int(row.get("changes", {}).get("updated", 0)) for row in rows),
            "would_update": sum(int(row.get("changes", {}).get("would_update", 0)) for row in rows),
            "removed": sum(int(row.get("changes", {}).get("removed", 0)) for row in rows),
            "would_remove": sum(int(row.get("changes", {}).get("would_remove", 0)) for row in rows),
        }
        return {
            "name": "model_catalog_refresh_all",
            "write": write,
            "new_entries_enabled": enable,
            "online": online,
            "query": query,
            "limit": limit,
            "verbose": verbose,
            "provider_limits": provider_limits or {},
            "providers_total": len(rows),
            "providers_updated": sum(1 for row in rows if row.get("status") == "updated"),
            "providers_would_update": sum(1 for row in rows if row.get("status") == "would_update"),
            "providers_failed": sum(1 for row in rows if row.get("status") == "failed"),
            "providers_skipped_empty": len(skipped_providers),
            "changes": changes,
            "results": results,
            "skipped_providers": skipped_providers,
            "next_steps": _refresh_next_steps(write, changes),
        }

    def promote_generated(
        self,
        name: str,
        new_name: str | None = None,
        write: bool = False,
        keep_discovered: bool = True,
        overwrite: bool = False,
    ) -> dict[str, Any]:
        if not name or "/" in name or "\\" in name:
            raise ValueError("model entry name must be a simple name")
        target = new_name or name
        if not target or "/" in target or "\\" in target:
            raise ValueError("target model entry name must be a simple name")
        curated_models = _dict_of_dicts(self.config.get("models", {}))
        generated_models = _dict_of_dicts(self.generated_config.get("models", {}))
        if name not in generated_models:
            raise ValueError(f"discovered model entry not found: {name}")
        target_exists = target in curated_models
        if target_exists and not overwrite:
            raise ValueError(
                f"profile-owned model entry already exists: {target}; pass overwrite=True or use --overwrite after reviewing the existing entry"
            )
        promoted = dict(generated_models[name])
        promoted.pop("imported_by", None)
        promoted["promoted_from"] = name
        promoted["discovered_entry"] = name
        promoted["curated"] = True
        if write:
            curated_models[target] = promoted
            self.config["models"] = curated_models
            self.store.write_curated(self.config)
            if not keep_discovered:
                generated_models.pop(name, None)
                self.generated_config["models"] = generated_models
                self._write_generated_config()
        return {
            "name": "model_catalog_promote",
            "source": name,
            "target": target,
            "write": write,
            "keep_discovered": keep_discovered,
            "overwrite": overwrite,
            "target_exists": target_exists,
            "promoted": 1 if write else 0,
            "would_promote": 0 if write else 1,
            "removed_discovered": bool(write and not keep_discovered),
            "path": str(self.profile.root / "models.yaml"),
            "discovered_path": str(self._generated_path()),
            "model": promoted,
            "next_steps": _promote_next_steps(name, target, write, keep_discovered),
        }

    def remove_model(
        self,
        name: str,
        write: bool = True,
    ) -> dict[str, Any]:
        _validate_model_entry_name(name, "model entry name")
        curated_models = _dict_of_dicts(self.config.get("models", {}))
        if name not in curated_models:
            raise ValueError(f"profile-owned model entry not found: {name}")
        defaults = self.config.get("defaults", {})
        removed_defaults: list[str] = []
        if isinstance(defaults, dict):
            removed_defaults = sorted(role for role, value in defaults.items() if str(value) == name)
        if write:
            curated_models.pop(name, None)
            if isinstance(defaults, dict):
                for role in removed_defaults:
                    defaults.pop(role, None)
                self.config["defaults"] = defaults
            self.config["models"] = curated_models
            self._write_curated_config()
        return {
            "name": "model_catalog_remove",
            "entry": name,
            "write": write,
            "removed_curated": bool(write),
            "would_remove_curated": bool(not write),
            "removed_defaults": removed_defaults if write else [],
            "would_remove_defaults": removed_defaults if not write else [],
            "path": str(self.profile.root / "models.yaml"),
        }

    def clear_imported(
        self,
        provider_name: str | None = None,
        write: bool = False,
        include_curated: bool = True,
    ) -> dict[str, Any]:
        curated_models = _dict_of_dicts(self.config.get("models", {}))
        generated_models = _dict_of_dicts(self.generated_config.get("models", {}))
        removed_counts: dict[str, int] = {}
        removed_curated_counts: dict[str, int] = {}
        curated_dirty = False
        generated_dirty = False
        for name, model in list(generated_models.items()):
            if not isinstance(model, dict):
                continue
            source = model_source(model)
            if provider_name and source != provider_name:
                continue
            removed_counts[source] = removed_counts.get(source, 0) + 1
            if write:
                generated_models.pop(name, None)
                generated_dirty = True
        for name, model in list(curated_models.items()):
            if not isinstance(model, dict):
                continue
            is_imported = _is_refresh_imported_model(model)
            if not is_imported and not include_curated:
                continue
            source = model_source(model)
            if provider_name and source != provider_name:
                continue
            removed_counts[source] = removed_counts.get(source, 0) + 1
            if not is_imported:
                removed_curated_counts[source] = removed_curated_counts.get(source, 0) + 1
            if write:
                curated_models.pop(name, None)
                curated_dirty = True
        total_removed = sum(removed_counts.values())
        if write and total_removed:
            self.config["models"] = curated_models
            self.generated_config["models"] = generated_models
            if curated_dirty:
                self.store.write_curated(self.config)
            if generated_dirty:
                self._write_generated_config()
        provider_counts = [{"name": source, "count": count} for source, count in sorted(removed_counts.items())]
        curated_provider_counts = [
            {"name": source, "count": count} for source, count in sorted(removed_curated_counts.items())
        ]
        return {
            "name": "model_catalog_clear_cache",
            "write": write,
            "provider": provider_name,
            "include_curated": include_curated,
            "removed": total_removed if write else 0,
            "would_remove": 0 if write else total_removed,
            "provider_counts": provider_counts,
            "curated_provider_counts": curated_provider_counts,
            "path": str(self.profile.root / "models.yaml"),
            "discovered_path": str(self._generated_path()),
        }

    def _generated_path(self) -> Path:
        return self.store.generated_path

    def _write_generated_config(self) -> Path:
        return self.store.write_generated(self.generated_config)

    def _execution(self):
        from .model_execution import ModelExecution

        return ModelExecution(self)

    def pull_plan(self, name=None, source=None, model_id=None, for_runtime=None, file=None):
        return self._execution().pull_plan(name, source, model_id, for_runtime, file)

    def get(self, name: str) -> dict[str, Any]:
        return self._execution().get(name)

    def show(self, name: str) -> dict[str, Any]:
        return self._execution().show(name)

    def doctor(self) -> list[ModelStatus]:
        return self._execution().doctor()

    def pull(self, name: str) -> str:
        return self._execution().pull(name)

    def complete(
        self, name: str, prompt: str, timeout_seconds: int | None = None, purpose: str = "chat"
    ) -> BackendResult:
        return self._execution().complete(name, prompt, timeout_seconds, purpose)

    def require_execution_capability(self, name: str, model: dict[str, Any], purpose: str) -> None:
        self._execution().require_execution_capability(name, model, purpose)

    def test_prompt(self, name: str, task: str, target: Path | None = None, dry_run: bool = False) -> BackendResult:
        return self._execution().test_prompt(name, task, target, dry_run)


def capability_profile(model: dict[str, Any]) -> dict[str, Any]:
    configured = model.get("capability_scores")
    if isinstance(configured, dict):
        scores = {key: _int_or_zero(value) for key, value in configured.items()}
        source = str(model.get("capability_score_source", "configured"))
    else:
        scores = _heuristic_capability_scores(model)
        source = "catalog_heuristic"
    return {
        "score_scale": "0-5",
        "score_source": source,
        "scores": scores,
        "benchmark_refs": _benchmark_refs(model),
        "notes": "Scores are suitability signals, not absolute benchmark percentages.",
    }


def _heuristic_capability_scores(model: dict[str, Any]) -> dict[str, int]:
    model_id = str(model.get("model", "")).lower()
    roles = {str(role) for role in model.get("roles", []) if role}
    params = _parameter_billions(model_id)
    is_cloud = not bool(model.get("local", False))
    is_embedding = "embed" in model_id or "embedding" in roles
    is_code = any(token in model_id for token in ["coder", "code"]) or "completion" in roles
    is_reasoning = "reason" in model_id or "reasoning" in roles
    is_general = "chat" in roles or "generation" in roles

    if is_embedding:
        return {
            "code_analysis": 0,
            "code_generation": 0,
            "code_completion": 0,
            "debugging_refactor": 0,
            "reasoning": 0,
            "math": 0,
            "tool_use": 0,
            "general_chat": 0,
            "embedding": 5,
            "vision_image_understanding": 0,
            "image_generation": 0,
            "audio": 0,
            "video": 0,
        }
    if "text_to_speech" in roles:
        return {
            "text_to_speech": 4,
            "speech_to_text": 0,
            "image_generation": 0,
            "video_generation": 0,
            "audio": 4,
            "video": 0,
        }
    if "speech_to_text" in roles:
        return {
            "text_to_speech": 0,
            "speech_to_text": 4,
            "image_generation": 0,
            "video_generation": 0,
            "audio": 4,
            "video": 0,
        }
    if "image_generation" in roles:
        return {
            "text_to_speech": 0,
            "speech_to_text": 0,
            "image_generation": 4,
            "video_generation": 0,
            "audio": 0,
            "video": 0,
        }
    if "video_generation" in roles:
        return {
            "text_to_speech": 0,
            "speech_to_text": 0,
            "image_generation": 2,
            "video_generation": 4,
            "audio": 0,
            "video": 4,
        }

    code_base = 1
    if is_code:
        code_base = 2 + _size_bonus(params)
    elif is_reasoning or is_general:
        code_base = 1 + min(_size_bonus(params), 2)
    if is_cloud:
        code_base = max(code_base, 4)

    reasoning = 1 + min(_size_bonus(params), 3)
    if is_reasoning:
        reasoning = min(5, reasoning + 1)
    if is_cloud:
        reasoning = max(reasoning, 4)

    instruction = 2 + min(_size_bonus(params), 2)
    if is_cloud:
        instruction = max(instruction, 4)

    completion = code_base if "completion" in roles or is_code else max(1, code_base - 1)

    return {
        "code_analysis": _clamp(code_base),
        "code_generation": _clamp(code_base),
        "code_completion": _clamp(completion),
        "debugging_refactor": _clamp(code_base - (0 if params >= 14 else 1)),
        "reasoning": _clamp(reasoning),
        "math": _clamp(reasoning if is_reasoning else reasoning - 1),
        "tool_use": _clamp(instruction if params >= 7 or is_cloud else instruction - 1),
        "general_chat": _clamp(instruction),
        "embedding": 0,
        "vision_image_understanding": 0,
        "image_generation": 0,
        "audio": 0,
        "video": 0,
    }


def _benchmark_refs(model: dict[str, Any]) -> list[str]:
    roles = {str(role) for role in model.get("roles", []) if role}
    refs = []
    if roles.intersection({"completion", "autocomplete", "analysis", "generation", "refactor"}):
        refs.extend(["HumanEval", "MBPP", "LiveCodeBench", "SWE-bench-style repair tasks"])
    if "reasoning" in roles:
        refs.extend(["MATH", "GPQA", "LiveCodeBench"])
    if "chat" in roles:
        refs.extend(["MMLU/MMLU-Pro", "GPQA", "IFEval", "Arena-style preference evals"])
    if not refs:
        refs.append("catalog heuristic; no specific benchmark reference configured")
    return list(dict.fromkeys(refs))


def _clamp(value: int) -> int:
    return max(0, min(5, int(value)))


def _int_or_zero(value: object) -> int:
    try:
        return _clamp(int(value))
    except (TypeError, ValueError):
        return 0


def _validate_model_entry_name(name: str, label: str = "model entry name") -> None:
    if not name or "/" in name or "\\" in name:
        raise ValueError(f"{label} must be a simple name")


def _model_entry_next_steps(name: str, write: bool) -> list[str]:
    if not write:
        return [f"Run without --dry-run to write {name!r} to models.yaml."]
    return [
        f"Run aiplane models show {name} to review the model entry.",
        "Run aiplane profiles validate to check profile consistency.",
    ]


def _string_list(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(item) for item in value if str(item)]
    if isinstance(value, tuple):
        return [str(item) for item in value if str(item)]
    text = str(value)
    return [text] if text else []


def _metadata_number(metadata: dict[str, Any], key: str) -> float:
    value = metadata.get(key)
    if isinstance(value, str):
        value = value.replace(",", "").strip()
    number = _number_or_none(value)
    return float(number or 0)


def _benchmark_score(row: dict[str, Any]) -> float:
    benchmark = row.get("latest_benchmark")
    if not isinstance(benchmark, dict):
        return 0.0
    try:
        return float(benchmark.get("average_score", 0) or 0)
    except (TypeError, ValueError):
        return 0.0


def _role_score_for_row(row: dict[str, Any], roles: list[str]) -> float:
    if not roles:
        return 0.0
    scores = row.get("capabilities", {}).get("scores", {}) if isinstance(row.get("capabilities"), dict) else {}
    role_scores: list[float] = []
    for role in roles:
        capabilities = ROLE_CAPABILITY_MAP.get(role, [])
        if not capabilities:
            continue
        role_scores.append(
            sum(float(scores.get(capability, 0) or 0) for capability in capabilities) / len(capabilities)
        )
    if not role_scores:
        return 0.0
    return round(sum(role_scores) / len(role_scores), 2)


def _recommendation_row(row: dict[str, Any], roles: list[str]) -> dict[str, Any]:
    payload = dict(row)
    if roles:
        payload["matched_roles"] = [role for role in roles if role in row.get("roles", [])]
        payload["role_score"] = _role_score_for_row(row, roles)
        payload["role_capabilities"] = {role: ROLE_CAPABILITY_MAP.get(role, []) for role in roles}
    else:
        payload["role_score"] = None
    return payload


ROLE_CAPABILITY_MAP: dict[str, list[str]] = {
    "chat": ["general_chat", "reasoning", "tool_use"],
    "autocomplete": ["code_completion"],
    "embedding": ["embedding"],
    "analysis": ["code_analysis", "reasoning"],
    "generation": ["code_generation", "general_chat"],
    "refactor": ["debugging_refactor", "code_analysis"],
    "image_generation": ["image_generation"],
    "text_to_speech": ["text_to_speech"],
    "speech_to_text": ["speech_to_text"],
    "video_generation": ["video_generation", "video"],
}

CAPABILITY_ALIASES: dict[str, list[str]] = {
    "coding": ["code_generation", "code_analysis", "code_completion"],
    "autocomplete": ["code_completion"],
    "debugging": ["debugging_refactor"],
    "reasoning": ["reasoning"],
    "chat": ["general_chat"],
    "embedding": ["embedding"],
    "tool_use": ["tool_use"],
    "stt": ["speech_to_text"],
    "tts": ["text_to_speech"],
    "audio": ["audio"],
    "image": ["image_generation", "vision_image_understanding"],
    "video": ["video_generation", "video"],
}


def top_capabilities(profile: dict[str, Any], limit: int = 3) -> list[dict[str, Any]]:
    scores = profile.get("scores", {}) if isinstance(profile, dict) else {}
    rows = [{"name": name, "score": score} for name, score in scores.items() if isinstance(score, int) and score > 0]
    return sorted(rows, key=lambda row: (-int(row["score"]), str(row["name"])))[:limit]


def capability_tags(profile: dict[str, Any], minimum: int = 3) -> list[str]:
    scores = profile.get("scores", {}) if isinstance(profile, dict) else {}
    tags = []
    for tag, keys in CAPABILITY_ALIASES.items():
        values = [int(scores.get(key, 0)) for key in keys]
        if values and max(values) >= minimum:
            tags.append(tag)
    return tags


def model_source(model: dict[str, Any]) -> str:
    if model.get("source"):
        return str(model.get("source"))
    provider = str(model.get("provider", ""))
    model_id = str(model.get("model", ""))
    if provider in {"ollama", "ollama_cloud"}:
        return "ollama"
    if provider in {"vllm", "tgi", "transformers"} or "/" in model_id:
        return "huggingface"
    if provider in {"llamacpp", "localai"} or model_id.endswith(".gguf"):
        return "huggingface_gguf"
    if provider in {"openai", "anthropic", "azure_openai"}:
        return provider
    return provider or "unknown"


def ownership_for_model(model: dict[str, Any], provider: dict[str, Any]) -> str:
    if model.get("ownership"):
        return str(model.get("ownership"))
    if provider.get("ownership"):
        return str(provider.get("ownership"))
    provider_name = str(model.get("provider", ""))
    if provider_name in {"openai", "anthropic", "azure_openai", "ollama_cloud"}:
        return "managed_service"
    return "self_managed"


def parse_capability_filter(value: str) -> tuple[str, int]:
    for operator in [">=", ":"]:
        if operator in value:
            name, threshold = value.split(operator, 1)
            return name.strip(), _clamp(int(threshold.strip()))
    return value.strip(), 1


def expand_capability_filters(values: list[str]) -> dict[str, int]:
    expanded: dict[str, int] = {}
    for value in values:
        name, threshold = parse_capability_filter(value)
        keys = CAPABILITY_ALIASES.get(name, [name])
        for key in keys:
            expanded[key] = max(expanded.get(key, 0), threshold)
    return expanded


def _capability_average(profile: dict[str, Any]) -> float:
    scores = profile.get("scores", {}) if isinstance(profile, dict) else {}
    values = [int(value) for value in scores.values() if isinstance(value, int)]
    return round(sum(values) / len(values), 2) if values else 0.0


def _refresh_failure_next_steps(provider_name: str) -> list[str]:
    return [
        f"Run aiplane providers show {provider_name} to inspect endpoint, auth, and catalog adapter settings.",
        f"Run aiplane providers test {provider_name} after configuring credentials or endpoint overrides.",
        f"Rerun aiplane models refresh --provider {provider_name} --dry-run once provider discovery is configured.",
    ]


def _refresh_next_steps(write: bool, changes: dict[str, int], provider_name: str | None = None) -> list[str]:
    provider_flag = f" --provider {provider_name}" if provider_name else ""
    if not write:
        steps = [
            f"Review this dry-run output, then run aiplane models refresh{provider_flag} without --dry-run to write discovered entries."
        ]
    else:
        steps = [
            "Review discovered entries in models.discovered.yaml before promoting any of them into profile-owned models.yaml entries."
        ]
    if int(changes.get("would_import", 0)) or int(changes.get("imported", 0)):
        steps.append(
            "Use aiplane models promote DISCOVERED_ENTRY_NAME --dry-run to preview promoting one discovered entry."
        )
    if int(changes.get("would_update", 0)) or int(changes.get("updated", 0)):
        steps.append("Inspect updated source metadata before relying on changed capability or runtime-fit fields.")
    if int(changes.get("would_remove", 0)) or int(changes.get("removed", 0)):
        steps.append(
            "Confirm stale discovered entries are safe to prune; profile-owned entries are preserved by normal refresh."
        )
    steps.append("Use aiplane models clear-cache --dry-run to preview removing discovery refresh/import entries.")
    return steps


def _promote_next_steps(source: str, target: str, write: bool, keep_discovered: bool) -> list[str]:
    if not write:
        return [
            f"Review the promoted model payload, then run aiplane models promote {source} --as {target} without --dry-run to write models.yaml.",
            "After promotion, run aiplane models defaults or aiplane integrations plan to verify the profile-owned entry is selected where expected.",
        ]
    steps = [
        f"Profile-owned model entry {target} was written to models.yaml.",
        "Run aiplane profiles validate local-dev and aiplane integrations plan for the target tool before using the model entry in a workflow.",
    ]
    if keep_discovered:
        steps.append(f"Discovered entry {source} was kept in models.discovered.yaml for comparison.")
    else:
        steps.append(
            f"Discovered entry {source} was removed from models.discovered.yaml so the profile-owned entry is authoritative."
        )
    return steps


def _refresh_status(changes: dict[str, int]) -> str:
    if int(changes.get("imported", 0)) > 0 or int(changes.get("updated", 0)) > 0 or int(changes.get("removed", 0)) > 0:
        return "updated"
    if (
        int(changes.get("would_import", 0)) > 0
        or int(changes.get("would_update", 0)) > 0
        or int(changes.get("would_remove", 0)) > 0
    ):
        return "would_update"
    return "ok"


def _refresh_model_row(
    name: str,
    model: dict[str, Any],
    runtime_catalog: Any,
    refresh_status: str,
    provider_visible: bool | None,
    provider_reason: str,
) -> dict[str, Any]:
    source = runtime_catalog.source_for_model(model)
    preferred = model.get("preferred_runtime") or model.get("provider")
    provider_name = str(model.get("provider") or "")
    provider = runtime_catalog._providers().get(provider_name, {})
    ownership = ownership_for_model(model, provider)
    row = {
        "name": name,
        "model": {"id": model.get("model"), "source": source},
        "runtime_endpoint": provider_name,
        "ownership": ownership,
        "refresh_status": refresh_status,
        "enabled": bool(model.get("enabled", True)),
        "provider_visible": provider_visible,
        "local_presence": _refresh_local_presence(ownership, provider_name, provider_visible),
        "provider_reason": provider_reason,
        "preferred_runtime": preferred,
        "suitable_runtimes": runtime_catalog.compatible_runtimes_for_entry(model),
    }
    for key in [
        "roles",
        "local",
        "api_key_env",
        "pull_command",
        "min_ram_gb",
        "recommended_ram_gb",
        "min_vram_gb",
        "recommended_vram_gb",
        "context_window_tokens",
        "max_output_tokens",
        "supports_tool_calling",
        "supports_streaming",
        "notes",
    ]:
        if key in model and key not in row:
            row[key] = model[key]
    return row


def _refresh_local_presence(ownership: str, provider_name: str, provider_visible: bool | None) -> str:
    if ownership == "managed_service":
        return "not_applicable_managed_service"
    if provider_visible is True:
        return "present" if provider_name != "ollama" else "pulled"
    if provider_visible is False:
        return "not_listed" if provider_name != "ollama" else "not_pulled"
    return "not_checked"


def _group_refresh_catalog_rows(
    rows: list[dict[str, Any]],
) -> dict[str, dict[str, list[dict[str, Any]]]]:
    grouped: dict[str, dict[str, list[dict[str, Any]]]] = {}
    for row in rows:
        ownership = str(row.get("ownership") or "unknown")
        provider = str(
            (row.get("model") or {}).get("source")
            if isinstance(row.get("model"), dict)
            else row.get("source") or "unknown"
        )
        grouped.setdefault(ownership, {}).setdefault(provider, []).append(row)
    return {
        ownership: {
            provider: sorted(items, key=lambda item: str(item.get("name") or ""))
            for provider, items in sorted(providers.items())
        }
        for ownership, providers in sorted(grouped.items())
    }


def _unique_model_alias(models: dict[str, Any], provider_name: str, model_id: str) -> str:
    import re

    base = re.sub(r"[^a-z0-9]+", "-", model_id.lower()).strip("-")
    if provider_name and not base.startswith(provider_name + "-"):
        base = f"{provider_name}-{base}"
    name = base or "model"
    suffix = 2
    while name in models:
        name = f"{base}-{suffix}"
        suffix += 1
    return name


def _discovered_model_entry(
    provider_name: str,
    model_id: str,
    enable: bool = False,
    source_metadata: dict[str, Any] | None = None,
) -> dict[str, Any]:
    params = _parameter_billions(model_id.lower())
    roles = _roles_for_discovered_model(provider_name, model_id, source_metadata or {})
    min_ram, recommended_ram, min_vram, recommended_vram = _resource_guess(params, roles)
    resource_source = "catalog_heuristic:parameter_size_and_role"
    overrides = _resource_requirements_from_source_metadata(source_metadata or {})
    if overrides:
        if overrides.get("min_ram_gb") is not None:
            min_ram = overrides["min_ram_gb"]
        if overrides.get("recommended_ram_gb") is not None:
            recommended_ram = overrides["recommended_ram_gb"]
        if overrides.get("min_vram_gb") is not None:
            min_vram = overrides["min_vram_gb"]
        if overrides.get("recommended_vram_gb") is not None:
            recommended_vram = overrides["recommended_vram_gb"]
        if isinstance(overrides.get("resource_estimate_source"), str) and overrides.get("resource_estimate_source"):
            resource_source = str(overrides["resource_estimate_source"])
        else:
            resource_source = "provider_catalog:source_metadata"
    preferred_runtime = _preferred_runtime_for_discovered_roles(provider_name, roles)
    managed_sources = {
        "openai",
        "anthropic",
        "azure_openai",
        "ollama_cloud",
        "azure_speech",
        "elevenlabs",
    }
    entry: dict[str, Any] = {
        "provider": (provider_name if provider_name in managed_sources else preferred_runtime),
        "model": model_id,
        "roles": roles,
        "local": provider_name not in managed_sources,
        "enabled": enable,
        "source": provider_name,
        "preferred_runtime": preferred_runtime,
        "notes": "Discovered from model provider and imported into the editable profile catalog.",
        "imported_by": "aiplane_refresh",
        "min_ram_gb": min_ram,
        "recommended_ram_gb": recommended_ram,
        "min_vram_gb": min_vram,
        "resource_estimate_source": resource_source,
        "source_metadata": source_metadata or {},
    }
    supported_runtimes = _supported_runtimes_for_discovered_roles(roles)
    if supported_runtimes:
        entry["supported_runtimes"] = supported_runtimes
    if recommended_vram is not None:
        entry["recommended_vram_gb"] = recommended_vram
    if provider_name == "ollama":
        entry["pull_command"] = f"ollama pull {model_id}"
    elif provider_name == "huggingface":
        entry["pull_command"] = (
            f"python -c \"from huggingface_hub import snapshot_download; snapshot_download('{model_id}')\""
        )
    elif provider_name == "huggingface_gguf":
        entry["pull_command"] = (
            f"python -c \"from huggingface_hub import snapshot_download; snapshot_download('{model_id}')\""
        )
    elif provider_name == "civitai":
        entry["pull_command"] = (
            "download via Civitai model/version API and place checkpoint in the target runtime model directory"
        )
    if any(
        role in roles
        for role in [
            "embedding",
            "text_to_speech",
            "speech_to_text",
            "image_generation",
            "video_generation",
        ]
    ):
        entry["capability_scores"] = _heuristic_capability_scores(entry)
        entry["capability_score_source"] = "catalog_heuristic"
    return entry


def _merge_source_discovered_model(
    existing: dict[str, Any],
    provider_name: str,
    model_id: str,
    source_metadata: dict[str, Any] | None = None,
) -> dict[str, Any]:
    merged = dict(existing)
    discovered = _discovered_model_entry(
        provider_name,
        model_id,
        enable=bool(existing.get("enabled", True)),
        source_metadata=source_metadata or {},
    )
    source_fields = [
        "model",
        "source",
        "local",
        "pull_command",
        "source_metadata",
    ]
    if _is_refresh_imported_model(existing):
        source_fields.extend(
            [
                "provider",
                "preferred_runtime",
                "roles",
                "notes",
                "imported_by",
                "min_ram_gb",
                "recommended_ram_gb",
                "min_vram_gb",
                "recommended_vram_gb",
                "resource_estimate_source",
            ]
        )
        if "capability_scores" not in existing and "capability_scores" in discovered:
            source_fields.extend(["capability_scores", "capability_score_source"])
    for field in source_fields:
        if field in discovered:
            merged[field] = discovered[field]
        elif field in {"recommended_vram_gb"} and field in merged:
            merged.pop(field, None)
    return merged


def _is_refresh_imported_model(model: dict[str, Any]) -> bool:
    if model.get("imported_by") == "aiplane_refresh":
        return True
    notes = str(model.get("notes") or "")
    return notes.startswith("Discovered from model provider") or notes.startswith("Discovered from provider")


def _preferred_runtime_for_source(provider_name: str) -> str:
    if provider_name == "ollama":
        return "ollama"
    if provider_name == "huggingface":
        return "vllm"
    if provider_name == "huggingface_gguf":
        return "llamacpp"
    if provider_name == "civitai":
        return "comfyui"
    if provider_name == "azure_speech":
        return "azure_speech"
    if provider_name == "elevenlabs":
        return "elevenlabs"
    if provider_name == "modelscope":
        return "transformers"
    return provider_name


def _preferred_runtime_for_discovered_roles(provider_name: str, roles: list[str]) -> str:
    role_set = set(roles)
    if "video_generation" in role_set or "image_generation" in role_set:
        return "diffusers"
    if "speech_to_text" in role_set:
        return "faster_whisper"
    if "text_to_speech" in role_set:
        if provider_name in {"azure_speech", "elevenlabs"}:
            return provider_name
        return "transformers"
    return _preferred_runtime_for_source(provider_name)


def _supported_runtimes_for_discovered_roles(roles: list[str]) -> list[str]:
    role_set = set(roles)
    if "video_generation" in role_set or "image_generation" in role_set:
        return ["diffusers", "comfyui"]
    if "speech_to_text" in role_set:
        return ["faster_whisper", "transformers"]
    if "text_to_speech" in role_set:
        return ["transformers"]
    return []


def _resource_requirements_from_source_metadata(source_metadata: dict[str, Any]) -> dict[str, float | str]:
    if not isinstance(source_metadata, dict):
        return {}
    candidates: list[dict[str, Any]] = [source_metadata]
    for key in ["resources", "resource_requirements", "requirements", "hardware"]:
        value = source_metadata.get(key)
        if isinstance(value, dict):
            candidates.append(value)

    def _first_number(keys: list[str]) -> float | None:
        for block in candidates:
            for key in keys:
                value = _number_or_none(block.get(key))
                if value is not None:
                    return value
        return None

    min_ram = _first_number(["min_ram_gb", "minimum_ram_gb"])
    rec_ram = _first_number(["recommended_ram_gb"])
    min_vram = _first_number(["min_vram_gb", "minimum_vram_gb"])
    rec_vram = _first_number(["recommended_vram_gb"])
    if all(value is None for value in [min_ram, rec_ram, min_vram, rec_vram]):
        return {}
    source = None
    for block in candidates:
        value = block.get("resource_estimate_source")
        if isinstance(value, str) and value.strip():
            source = value.strip()
            break
    payload: dict[str, float | str] = {}
    if min_ram is not None:
        payload["min_ram_gb"] = min_ram
    if rec_ram is not None:
        payload["recommended_ram_gb"] = rec_ram
    if min_vram is not None:
        payload["min_vram_gb"] = min_vram
    if rec_vram is not None:
        payload["recommended_vram_gb"] = rec_vram
    if source:
        payload["resource_estimate_source"] = source
    return payload


def _roles_for_discovered_model(provider_name: str, model_id: str, source_metadata: dict[str, Any]) -> list[str]:
    pipeline = str(source_metadata.get("pipeline_tag") or "").lower().strip()
    tags = (
        {str(tag).lower() for tag in source_metadata.get("tags", []) if tag}
        if isinstance(source_metadata.get("tags"), list)
        else set()
    )
    if pipeline in {"feature-extraction", "sentence-similarity"} or "sentence-transformers" in tags:
        return ["embedding"]
    if pipeline in {"automatic-speech-recognition", "audio-to-text"}:
        return ["speech_to_text"]
    if pipeline in {"text-to-speech"}:
        return ["text_to_speech"]
    if pipeline in {
        "text-to-image",
        "image-to-image",
        "unconditional-image-generation",
    }:
        return ["image_generation"]
    if pipeline in {"image-to-video", "text-to-video", "video-to-video"}:
        return ["video_generation"]
    if pipeline in {
        "image-classification",
        "object-detection",
        "image-segmentation",
        "zero-shot-image-classification",
    }:
        return ["image_classification"]
    if pipeline in {"visual-question-answering", "image-to-text"}:
        return ["analysis", "vision"]
    if pipeline in {"text-generation", "text2text-generation", "conversational"}:
        return _roles_for_model_id(model_id)
    if provider_name == "huggingface" and pipeline and not pipeline.startswith("text"):
        return [pipeline.replace("-", "_")]
    return _roles_for_model_id(model_id)


def _roles_for_model_id(model_id: str) -> list[str]:
    value = model_id.lower()
    if "embed" in value:
        return ["embedding"]
    if any(
        token in value
        for token in [
            "stt",
            "speech-to-text",
            "speech_to_text",
            "automatic-speech-recognition",
        ]
    ):
        return ["speech_to_text"]
    if any(token in value for token in ["tts", "text-to-speech"]):
        return ["text_to_speech"]
    if any(token in value for token in ["text-to-image", "texttoimage", "image-generation"]):
        return ["image_generation"]
    if any(token in value for token in ["text-to-video", "texttovideo", "video-generation", "t2v"]):
        return ["video_generation"]
    if any(token in value for token in ["vision", "visual", "image-to-text", "visual-question-answering"]):
        return ["chat", "analysis", "vision"]
    if "coder" in value or "code" in value:
        if "base" in value:
            return ["completion", "autocomplete"]
        return ["analysis", "completion", "autocomplete", "generation"]
    return ["chat", "analysis", "generation"]


def build_smoke_prompt(task: str, target: Path | None = None) -> str:
    task = task.lower().strip()
    if task not in {"analysis", "completion", "write"}:
        raise ValueError("task must be one of: analysis, completion, write")
    source = ""
    if target is not None:
        source = target.read_text(encoding="utf-8")
    if task == "analysis":
        return (
            "Explain what this code does, identify one risk, and suggest one small improvement.\n\n```python\n"
            + source
            + "\n```"
        )
    if task == "completion":
        return (
            "Complete the following Python function. Return only code.\n\n```python\ndef add_numbers(a, b):\n"
            + (source or "    ")
            + "\n```"
        )
    return "Write a small Python function named is_even(value) and a unittest test case for it. Return only code."


def _dict_of_dicts(value: object) -> dict[str, dict[str, Any]]:
    if not isinstance(value, dict):
        return {}
    return {str(key): inner for key, inner in value.items() if isinstance(inner, dict)}
