from __future__ import annotations

from typing import Any


RUNTIME_DEFINITIONS: dict[str, dict[str, Any]] = {
    "ollama": {
        "ownership": "self_managed",
        "description": "Local/headless Ollama runtime with its own model library and Modelfile/GGUF import path",
        "managed_by_helper": True,
        "gui_required": False,
        "protocol": "ollama_api",
        "model_sources": ["ollama", "gguf_import"],
        "good_for": ["simple local setup", "CPU laptop", "single-user workstation"],
        "install_hint": "scripts/provider_helper.sh --provider ollama --action install",
    },
    "docker_model_runner": {
        "ownership": "self_managed",
        "description": "Docker Model Runner local inference service and OCI model store",
        "managed_by_helper": True,
        "gui_required": False,
        "protocol": "openai_compatible",
        "model_sources": ["docker_model", "huggingface_gguf", "local_file"],
        "good_for": ["Docker-managed local inference", "OpenAI-compatible clients", "portable OCI model identities"],
        "install_hint": "Install a Docker release with the docker model command, then run aiplane runtimes install docker_model_runner --yes",
    },
    "mlx": {
        "ownership": "self_managed",
        "description": "Apple Silicon inference server built on MLX and Hugging Face model identities",
        "managed_by_helper": "partial",
        "gui_required": False,
        "protocol": "openai_compatible",
        "model_sources": ["huggingface", "local_file"],
        "good_for": ["Apple Silicon", "unified-memory Macs", "local OpenAI-compatible serving"],
        "install_hint": "python -m pip install mlx-lm",
    },
    "azure_speech": {
        "ownership": "managed_service",
        "description": "Azure AI Speech managed text-to-speech service",
        "managed_by_helper": False,
        "gui_required": False,
        "protocol": "azure_speech",
        "model_sources": ["azure_speech"],
        "good_for": [
            "managed text to speech",
            "demo narration",
            "cloud audio generation",
        ],
        "install_hint": "Configure AZURE_SPEECH_KEY and AZURE_SPEECH_REGION, or use a credential reference in the profile.",
    },
    "vllm": {
        "description": "GPU-focused OpenAI-compatible server for Hugging Face Transformers-style models",
        "managed_by_helper": True,
        "gui_required": False,
        "protocol": "openai_compatible",
        "model_sources": ["huggingface", "nvidia"],
        "good_for": [
            "shared GPU workstation",
            "Azure/AWS GPU VM",
            "high-throughput inference",
        ],
        "install_hint": "python -m pip install vllm",
    },
    "llamacpp": {
        "description": "llama.cpp server for GGUF models, good on CPU and modest GPUs",
        "managed_by_helper": "partial",
        "gui_required": False,
        "protocol": "openai_compatible",
        "model_sources": ["huggingface_gguf", "local_file"],
        "good_for": ["CPU laptop", "quantized local models", "portable shared VM"],
        "install_hint": "Install llama.cpp and put llama-server on PATH",
    },
    "tgi": {
        "description": "Hugging Face Text Generation Inference server for HF model repos",
        "managed_by_helper": True,
        "gui_required": False,
        "protocol": "openai_compatible",
        "model_sources": ["huggingface", "nvidia"],
        "good_for": ["server inference", "containerized GPU endpoints"],
        "install_hint": "Run the ghcr.io/huggingface/text-generation-inference container or native TGI install",
    },
    "transformers": {
        "description": "Hugging Face Transformers Python library for direct scripts, experiments, training, and fine-tuning",
        "managed_by_helper": "partial",
        "gui_required": False,
        "protocol": "python_library",
        "model_sources": ["huggingface", "nvidia"],
        "good_for": ["experiments", "training", "fine-tuning", "evaluation scripts"],
        "install_hint": "python -m pip install transformers accelerate torch",
    },
    "localai": {
        "description": "OpenAI-compatible local server that can run multiple backends, including GGUF/llama.cpp-style models",
        "managed_by_helper": "partial",
        "gui_required": False,
        "protocol": "openai_compatible",
        "model_sources": ["huggingface_gguf", "local_file"],
        "good_for": ["OpenAI-compatible local service", "mixed backend experiments"],
        "install_hint": "Install/run LocalAI from its container or native release",
    },
    "faster_whisper": {
        "description": "Speech-to-text runtime/library for speech-to-text models, optimized for local CPU/GPU transcription",
        "managed_by_helper": "planned",
        "gui_required": False,
        "protocol": "python_library",
        "model_sources": ["huggingface", "local_file"],
        "good_for": ["speech to text", "local transcription", "batch audio jobs"],
        "install_hint": "python -m pip install faster-whisper",
    },
    "diffusers": {
        "description": "Hugging Face Diffusers Python library for image/video/audio generation pipelines",
        "managed_by_helper": "planned",
        "gui_required": False,
        "protocol": "python_library",
        "model_sources": ["huggingface", "local_file"],
        "good_for": [
            "image generation",
            "video generation experiments",
            "pipeline prototyping",
        ],
        "install_hint": "python -m pip install diffusers transformers accelerate torch",
    },
    "comfyui": {
        "description": "Node-based image/video generation runtime with a web UI and local API",
        "managed_by_helper": "planned",
        "gui_required": True,
        "protocol": "local_api",
        "model_sources": ["huggingface", "local_file"],
        "good_for": [
            "image workflows",
            "video workflows",
            "visual generation pipelines",
        ],
        "install_hint": "Install ComfyUI, place checkpoints under its models directory, and start its server",
    },
    "lmstudio": {
        "description": "Desktop model catalog and OpenAI-compatible local server",
        "managed_by_helper": False,
        "gui_required": True,
        "protocol": "openai_compatible",
        "model_sources": ["huggingface_gguf", "lmstudio_catalog"],
        "good_for": ["desktop local use", "manual model selection"],
        "install_hint": "Install LM Studio and start the local server from the GUI",
    },
}


SOURCE_DEFINITIONS: dict[str, dict[str, Any]] = {
    "ollama": {
        "ownership": "self_managed",
        "supported_apis": ["chat_completions"],
        "description": "Ollama model library and local pull store",
        "typical_runtimes": ["ollama"],
        "catalog_adapter": "ollama",
    },
    "docker_model": {
        "ownership": "self_managed",
        "supported_apis": ["chat_completions"],
        "description": "OCI-packaged models consumed by Docker Model Runner",
        "typical_runtimes": ["docker_model_runner"],
        "catalog_adapter": "profile_catalog",
    },
    "huggingface": {
        "ownership": "self_managed",
        "description": "Hugging Face Hub model repos with tokenizer/config/weights",
        "typical_runtimes": ["vllm", "mlx", "tgi", "transformers"],
        "catalog_adapter": "huggingface",
    },
    "nvidia": {
        "ownership": "self_managed",
        "description": "NVIDIA open model repos on Hugging Face, including Nemotron language, reasoning, retrieval, speech, vision, and safety models",
        "typical_runtimes": ["vllm", "tgi", "transformers"],
        "catalog_adapter": "huggingface",
        "huggingface_author": "nvidia",
    },
    "huggingface_gguf": {
        "ownership": "self_managed",
        "description": "GGUF model files hosted on Hugging Face or another file store",
        "typical_runtimes": ["llamacpp", "localai", "ollama"],
        "catalog_adapter": "huggingface_gguf",
    },
    "local_file": {
        "ownership": "self_managed",
        "description": "Local model path, usually GGUF, ONNX, checkpoint, or runtime-specific files",
        "enabled": False,
        "catalog_adapter": "profile_catalog",
        "typical_runtimes": [
            "llamacpp",
            "localai",
            "faster_whisper",
            "diffusers",
            "comfyui",
        ],
    },
    "azure_speech": {
        "ownership": "managed_service",
        "description": "Azure AI Speech voice deployments and voice names",
        "enabled": False,
        "endpoint_family": "azure_speech",
        "api_key_env": "AZURE_SPEECH_KEY",
        "auth": {"required": True, "method": "api_key"},
        "typical_runtimes": [],
        "catalog_adapter": "profile_catalog",
    },
    "elevenlabs": {
        "ownership": "managed_service",
        "description": "ElevenLabs hosted text-to-speech voices and voice models",
        "endpoint_family": "elevenlabs",
        "endpoint": "https://api.elevenlabs.io/v1",
        "api_key_env": "ELEVENLABS_API_KEY",
        "auth": {"required": True, "method": "api_key"},
        "typical_runtimes": [],
        "catalog_adapter": "elevenlabs",
    },
    "openai": {
        "ownership": "managed_service",
        "supported_apis": ["responses", "chat_completions"],
        "description": "OpenAI hosted model catalog and deployments",
        "endpoint_family": "openai",
        "endpoint": "https://api.openai.com/v1",
        "api_key_env": "OPENAI_API_KEY",
        "auth": {"required": True, "method": "bearer"},
        "typical_runtimes": [],
        "catalog_adapter": "openai",
    },
    "anthropic": {
        "ownership": "managed_service",
        "supported_apis": ["messages"],
        "description": "Anthropic hosted model catalog",
        "endpoint_family": "anthropic",
        "endpoint": "https://api.anthropic.com",
        "api_key_env": "ANTHROPIC_API_KEY",
        "auth": {"required": True, "method": "api_key"},
        "typical_runtimes": [],
        "catalog_adapter": "anthropic",
    },
    "azure_openai": {
        "ownership": "managed_service",
        "supported_apis": ["responses", "chat_completions"],
        "description": "Azure OpenAI deployments in a configured Azure OpenAI resource",
        "endpoint_family": "azure_openai",
        "api_key_env": "AZURE_OPENAI_API_KEY",
        "auth": {"required": True, "method": "api_key"},
        "typical_runtimes": [],
        "catalog_adapter": "azure_openai",
    },
    "ollama_cloud": {
        "ownership": "managed_service",
        "description": "Ollama Cloud hosted catalog and endpoints",
        "endpoint_family": "ollama_cloud",
        "endpoint": "https://ollama.com",
        "api_key_env": "OLLAMA_API_KEY",
        "auth": {"required": True, "method": "bearer"},
        "typical_runtimes": [],
        "catalog_adapter": "profile_catalog",
    },
}


PROVIDER_ENDPOINT_DEFAULTS: dict[str, dict[str, Any]] = {
    "ollama": {
        "supported_apis": ["chat_completions"],
        "ownership": "self_managed",
        "access": {"kind": "same_host"},
        "substrate": "native",
        "runtime": "ollama",
        "protocol": "ollama_api",
        "endpoint": "http://localhost:11434",
        "enabled": True,
        "timeout_seconds": 60,
        "origin": "default_runtime_catalog",
        "notes": "Conventional Ollama endpoint default. Doctor/test commands still verify whether Ollama is actually installed, running, and has the model pulled.",
    },
    "docker_model_runner": {
        "supported_apis": ["chat_completions"],
        "ownership": "self_managed",
        "access": {"kind": "same_host"},
        "substrate": "docker",
        "runtime": "docker_model_runner",
        "protocol": "openai_compatible",
        "endpoint": "http://localhost:12434/engines/v1",
        "enabled": False,
        "timeout_seconds": 60,
        "origin": "default_runtime_catalog",
        "notes": "Docker Model Runner host endpoint. Its local API is unauthenticated; do not expose it directly to untrusted networks.",
    },
    "mlx": {
        "supported_apis": ["chat_completions"],
        "ownership": "self_managed",
        "access": {"kind": "same_host"},
        "substrate": "venv",
        "runtime": "mlx",
        "protocol": "openai_compatible",
        "endpoint": "http://localhost:8080/v1",
        "enabled": False,
        "origin": "default_runtime_catalog",
        "notes": "Conventional MLX-LM server endpoint. Keep the development server private.",
    },
    "vllm": {
        "supported_apis": ["chat_completions"],
        "ownership": "self_managed",
        "access": {"kind": "same_host"},
        "substrate": "docker",
        "runtime": "vllm",
        "protocol": "openai_compatible",
        "endpoint": "http://localhost:8000/v1",
        "enabled": False,
        "origin": "default_runtime_catalog",
        "notes": "Conventional vLLM OpenAI-compatible endpoint default. Enable or override only after deploying the runtime.",
    },
    "lmstudio": {
        "supported_apis": ["responses", "chat_completions"],
        "ownership": "self_managed",
        "access": {"kind": "same_host"},
        "substrate": "native",
        "runtime": "lmstudio",
        "protocol": "openai_compatible",
        "endpoint": "http://localhost:1234/v1",
        "enabled": False,
        "origin": "default_runtime_catalog",
        "notes": "Conventional LM Studio local server endpoint default. Start/configure LM Studio before use.",
    },
    "llamacpp": {
        "supported_apis": ["chat_completions"],
        "ownership": "self_managed",
        "access": {"kind": "same_host"},
        "substrate": "native",
        "runtime": "llamacpp",
        "protocol": "openai_compatible",
        "endpoint": "http://localhost:8080/v1",
        "enabled": False,
        "origin": "default_runtime_catalog",
        "notes": "Conventional llama.cpp server endpoint default. Start/configure llama-server before use.",
    },
    "tgi": {
        "supported_apis": ["chat_completions"],
        "ownership": "self_managed",
        "access": {"kind": "same_host"},
        "substrate": "docker",
        "runtime": "tgi",
        "protocol": "openai_compatible",
        "endpoint": "http://localhost:8081/v1",
        "enabled": False,
        "origin": "default_runtime_catalog",
        "notes": "Conventional TGI endpoint default. Enable or override only after deploying the runtime.",
    },
    "transformers": {
        "ownership": "self_managed",
        "access": {"kind": "library"},
        "substrate": "venv",
        "runtime": "transformers",
        "protocol": "python_library",
        "enabled": False,
        "origin": "default_runtime_catalog",
        "notes": "Library runtime; no HTTP endpoint is implied.",
    },
    "localai": {
        "supported_apis": ["chat_completions"],
        "ownership": "self_managed",
        "access": {"kind": "same_host"},
        "substrate": "docker",
        "runtime": "localai",
        "protocol": "openai_compatible",
        "endpoint": "http://localhost:8082/v1",
        "enabled": False,
        "origin": "default_runtime_catalog",
        "notes": "Conventional LocalAI endpoint default. Enable or override only after deploying the runtime.",
    },
    "comfyui": {
        "ownership": "self_managed",
        "access": {"kind": "same_host"},
        "substrate": "native",
        "runtime": "comfyui",
        "protocol": "local_api",
        "endpoint": "http://localhost:8188",
        "enabled": False,
        "origin": "default_runtime_catalog",
        "notes": "Conventional ComfyUI endpoint default. Start/configure ComfyUI before use.",
    },
    "faster_whisper": {
        "ownership": "self_managed",
        "access": {"kind": "library"},
        "substrate": "venv",
        "runtime": "faster_whisper",
        "protocol": "python_library",
        "enabled": False,
        "origin": "default_runtime_catalog",
        "notes": "Library runtime; no HTTP endpoint is implied.",
    },
    "diffusers": {
        "ownership": "self_managed",
        "access": {"kind": "library"},
        "substrate": "venv",
        "runtime": "diffusers",
        "protocol": "python_library",
        "enabled": False,
        "origin": "default_runtime_catalog",
        "notes": "Library runtime; no HTTP endpoint is implied.",
    },
    "openai": {
        "supported_apis": ["responses", "chat_completions"],
        "ownership": "managed_service",
        "access": {"kind": "hosted_api"},
        "substrate": "managed_service",
        "runtime": "openai",
        "protocol": "openai_compatible",
        "endpoint": "https://api.openai.com/v1",
        "api_key_env": "OPENAI_API_KEY",
        "enabled": False,
        "origin": "default_runtime_catalog",
        "notes": "Hosted service endpoint default. Enable only after selecting profile-owned model entries and configuring credentials.",
    },
    "anthropic": {
        "supported_apis": ["messages"],
        "ownership": "managed_service",
        "access": {"kind": "hosted_api"},
        "substrate": "managed_service",
        "runtime": "anthropic",
        "protocol": "anthropic_api",
        "endpoint": "https://api.anthropic.com",
        "api_key_env": "ANTHROPIC_API_KEY",
        "enabled": False,
        "origin": "default_runtime_catalog",
        "notes": "Hosted service endpoint default. Enable only after configuring credentials.",
    },
    "azure_openai": {
        "supported_apis": ["responses", "chat_completions"],
        "ownership": "managed_service",
        "access": {"kind": "hosted_api"},
        "substrate": "azure",
        "runtime": "azure_openai",
        "protocol": "azure_openai",
        "endpoint": "",
        "api_version": "2024-02-01",
        "api_key_env": "AZURE_OPENAI_API_KEY",
        "enabled": False,
        "origin": "default_runtime_catalog",
        "notes": "Set endpoint to your Azure OpenAI resource URL and use deployment names as model ids.",
    },
    "ollama_cloud": {
        "ownership": "managed_service",
        "access": {"kind": "hosted_api"},
        "substrate": "managed_service",
        "runtime": "ollama_cloud",
        "protocol": "ollama_api",
        "endpoint": "https://ollama.com",
        "api_key_env": "OLLAMA_API_KEY",
        "enabled": False,
        "origin": "default_runtime_catalog",
        "notes": "Hosted Ollama-style endpoint default. Enable only when configured for your account.",
    },
    "azure_speech": {
        "ownership": "managed_service",
        "access": {"kind": "hosted_api"},
        "substrate": "azure",
        "runtime": "azure_speech",
        "protocol": "azure_speech",
        "endpoint": "",
        "api_key_env": "AZURE_SPEECH_KEY",
        "region_env": "AZURE_SPEECH_REGION",
        "enabled": False,
        "origin": "default_runtime_catalog",
        "notes": "Azure AI Speech service defaults. Configure endpoint/region/credentials before use.",
    },
    "elevenlabs": {
        "ownership": "managed_service",
        "access": {"kind": "hosted_api"},
        "substrate": "managed_service",
        "runtime": "elevenlabs",
        "protocol": "elevenlabs_tts",
        "endpoint": "https://api.elevenlabs.io/v1",
        "api_key_env": "ELEVENLABS_API_KEY",
        "enabled": False,
        "origin": "default_runtime_catalog",
        "notes": "ElevenLabs hosted TTS endpoint default. Enable only after configuring credentials.",
    },
}
