#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MODE="venv"
ACTION="install"
VENV_PATH="$PROJECT_ROOT/.venv"
CONDA_ENV="aiplane"
DOCKER_IMAGE="aiplane:local"
DOCKER_BASE_IMAGE="python:3.13-slim"
PYTHON_BIN="python"
DRY_RUN=0
UPDATE_PIP=1
INSTALL_MODE="editable"
ACTIVATE_AFTER_INSTALL=1

usage() {
  cat <<'USAGE'
Usage: scripts/setup_env.sh [options]

Actions:
  --action install     Create/configure the selected environment and install aiplane (default)
  --action doctor      Verify the selected environment can import and run aiplane
  --action test        Run the unit test suite in the selected environment

Modes:
  --mode local         Install into the current Python environment
  --mode venv          Create/use a Python venv (default: .venv)
  --mode conda         Create/use a Conda environment
  --mode docker        Build/use a Docker image that can run the aiplane CLI

Options:
  --venv-path PATH     venv path for --mode venv (default: .venv)
  --conda-env NAME     Conda env name for --mode conda (default: aiplane)
  --docker-image TAG   Docker image tag for --mode docker (default: aiplane:local)
  --docker-base IMAGE  Base image for --mode docker builds (default: python:3.13-slim)
  --python PATH        Python executable for local/venv creation (default: python)
  --install-mode MODE  Package install mode: editable/source-linked or static/snapshot (default: editable)
  --editable           Shortcut for --install-mode editable
  --static             Shortcut for --install-mode static
  --activate 0|1       For Conda install, activate env after install when sourced (default: 1)
  --no-pip-upgrade     Skip pip upgrade before package install
  --dry-run            Print commands without executing them
  -h, --help           Show this help

Examples:
  scripts/setup_env.sh --mode venv --action install --editable
  scripts/setup_env.sh --mode venv --action install --static
  scripts/setup_env.sh --mode venv --action doctor
  source scripts/setup_env.sh --mode conda --conda-env aiplane --action install --editable
  scripts/setup_env.sh --mode conda --conda-env aiplane --action install --static --activate 0
  scripts/setup_env.sh --mode local --action install --static
  scripts/setup_env.sh --mode docker --action install --editable --docker-image aiplane:dev
  scripts/setup_env.sh --mode docker --action install --static --docker-image aiplane:snapshot
USAGE
}

run() {
  printf '+'
  printf ' %q' "$@"
  printf '\n'
  if [[ "$DRY_RUN" -eq 0 ]]; then
    "$@"
  fi
}

run_shell() {
  printf '+ %s\n' "$*"
  if [[ "$DRY_RUN" -eq 0 ]]; then
    bash -lc "$*"
  fi
}


conda_available() {
  command -v conda >/dev/null 2>&1
}

conda_env_exists() {
  conda env list | awk 'NF && $1 !~ /^#/ {print $1}' | grep -Fxq "$CONDA_ENV"
}

write_conda_activation_helper() {
  mkdir -p "$PROJECT_ROOT/.aiplane"
  local helper="$PROJECT_ROOT/.aiplane/activate-conda-$CONDA_ENV.sh"
  cat >"$helper" <<EOF
# Source this file to activate the aiplane Conda environment in your current shell.
# Generated by scripts/setup_env.sh.
if ! command -v conda >/dev/null 2>&1; then
  echo "conda is not on PATH" >&2
  return 1
fi
eval "\$(conda shell.bash hook)"
conda activate "$CONDA_ENV"
EOF
  echo "Wrote activation helper: $helper"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode)
      MODE="${2:?missing value for --mode}"
      shift 2
      ;;
    --action)
      ACTION="${2:?missing value for --action}"
      shift 2
      ;;
    --venv-path)
      VENV_PATH="${2:?missing value for --venv-path}"
      [[ "$VENV_PATH" = /* ]] || VENV_PATH="$PROJECT_ROOT/$VENV_PATH"
      shift 2
      ;;
    --conda-env)
      CONDA_ENV="${2:?missing value for --conda-env}"
      shift 2
      ;;
    --docker-image)
      DOCKER_IMAGE="${2:?missing value for --docker-image}"
      shift 2
      ;;
    --docker-base)
      DOCKER_BASE_IMAGE="${2:?missing value for --docker-base}"
      shift 2
      ;;
    --python)
      PYTHON_BIN="${2:?missing value for --python}"
      shift 2
      ;;
    --install-mode)
      INSTALL_MODE="${2:?missing value for --install-mode}"
      shift 2
      ;;
    --editable)
      INSTALL_MODE="editable"
      ACTIVATE_AFTER_INSTALL=1
      shift
      ;;
    --static)
      INSTALL_MODE="static"
      shift
      ;;
    --activate)
      ACTIVATE_AFTER_INSTALL="${2:?missing value for --activate}"
      shift 2
      ;;
    --no-pip-upgrade)
      UPDATE_PIP=0
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

case "$MODE" in
  local|venv|conda|docker) ;;
  *) echo "Unsupported mode: $MODE" >&2; exit 2 ;;
esac

case "$ACTION" in
  install|doctor|test) ;;
  *) echo "Unsupported action: $ACTION" >&2; exit 2 ;;
esac

case "$INSTALL_MODE" in
  editable|source-linked|source_linked)
    INSTALL_MODE="editable"
    ACTIVATE_AFTER_INSTALL=1
    ;;
  static|snapshot)
    INSTALL_MODE="static"
    ;;
  *) echo "Unsupported install mode: $INSTALL_MODE" >&2; exit 2 ;;
esac

cd "$PROJECT_ROOT"

pip_install_args() {
  case "$INSTALL_MODE" in
    editable)
      printf '%s
' -e .
      ;;
    static)
      printf '%s
' .
      ;;
  esac
}

install_label() {
  case "$INSTALL_MODE" in
    editable)
      printf '%s
' "editable/source-linked"
      ;;
    static)
      printf '%s
' "static/snapshot"
      ;;
  esac
}

python_for_mode() {
  case "$MODE" in
    local)
      printf '%s\n' "$PYTHON_BIN"
      ;;
    venv)
      printf '%s\n' "$VENV_PATH/bin/python"
      ;;
    conda)
      printf 'conda run -n %q python\n' "$CONDA_ENV"
      ;;
    docker)
      printf 'docker run --rm -v %q:/workspace -w /workspace %q python\n' "$PROJECT_ROOT" "$DOCKER_IMAGE"
      ;;
  esac
}

install_local() {
  echo "Installing aiplane in $(install_label) mode into the current Python environment."
  if [[ "$UPDATE_PIP" -eq 1 ]]; then
    run "$PYTHON_BIN" -m pip install --upgrade pip
  fi
  run "$PYTHON_BIN" -m pip install $(pip_install_args)
}

install_venv() {
  echo "Installing aiplane in $(install_label) mode into venv: $VENV_PATH"
  if [[ ! -d "$VENV_PATH" ]]; then
    run "$PYTHON_BIN" -m venv "$VENV_PATH"
  fi
  if [[ "$UPDATE_PIP" -eq 1 ]]; then
    run "$VENV_PATH/bin/python" -m pip install --upgrade pip
  fi
  run "$VENV_PATH/bin/python" -m pip install $(pip_install_args)
}

install_conda() {
  echo "Installing aiplane in $(install_label) mode into Conda env: $CONDA_ENV"
  if ! conda_available; then
    echo "conda is not on PATH" >&2
    exit 1
  fi
  if ! conda_env_exists; then
    run conda create -n "$CONDA_ENV" python=3.13 -y
  else
    echo "Conda environment already exists: $CONDA_ENV"
  fi
  if [[ "$DRY_RUN" -eq 0 ]] && ! conda_env_exists; then
    echo "Conda environment was not created or is not visible: $CONDA_ENV" >&2
    echo "Check with: conda env list" >&2
    exit 1
  fi
  if [[ "$UPDATE_PIP" -eq 1 ]]; then
    run conda run -n "$CONDA_ENV" python -m pip install --upgrade pip
  fi
  run conda run -n "$CONDA_ENV" python -m pip install $(pip_install_args)
  if [[ "$DRY_RUN" -eq 0 ]]; then
    write_conda_activation_helper
  fi
}

install_docker() {
  echo "Installing aiplane in $(install_label) mode into Docker image: $DOCKER_IMAGE"
  if ! command -v docker >/dev/null 2>&1 && [[ "$DRY_RUN" -eq 0 ]]; then
    echo "docker is not on PATH" >&2
    exit 1
  fi
  mkdir -p "$PROJECT_ROOT/.aiplane/docker"
  local dockerfile="$PROJECT_ROOT/.aiplane/docker/setup_env.Dockerfile"
  case "$INSTALL_MODE" in
    editable)
      cat >"$dockerfile" <<EOF
FROM $DOCKER_BASE_IMAGE
WORKDIR /workspace
RUN python -m pip install --upgrade pip
# Editable/source-linked mode mounts the host checkout at /workspace when the container runs.
EOF
      ;;
    static)
      cat >"$dockerfile" <<EOF
FROM $DOCKER_BASE_IMAGE
WORKDIR /opt/aiplane
COPY . /opt/aiplane
RUN python -m pip install --upgrade pip && python -m pip install -e /opt/aiplane
WORKDIR /opt/aiplane
EOF
      ;;
  esac
  run docker build -t "$DOCKER_IMAGE" -f "$dockerfile" "$PROJECT_ROOT"
}

docker_run_aiplane() {
  case "$INSTALL_MODE" in
    editable)
      run docker run --rm -v "$PROJECT_ROOT:/workspace" -w /workspace "$DOCKER_IMAGE" sh -lc "python -m pip install -e . >/tmp/aiplane-install.log && python -m aiplane $*"
      ;;
    static)
      run docker run --rm "$DOCKER_IMAGE" python -m aiplane "$@"
      ;;
  esac
}

docker_run_shell() {
  case "$INSTALL_MODE" in
    editable)
      run docker run --rm -v "$PROJECT_ROOT:/workspace" -w /workspace "$DOCKER_IMAGE" sh -lc "python -m pip install -e . >/tmp/aiplane-install.log && $*"
      ;;
    static)
      run docker run --rm "$DOCKER_IMAGE" sh -lc "$*"
      ;;
  esac
}

doctor_mode() {
  case "$MODE" in
    local)
      run "$PYTHON_BIN" -m aiplane profiles list
      run "$PYTHON_BIN" -c "import importlib.metadata as m; print(m.version(\"aiplane\"))"
      run "$PYTHON_BIN" -m aiplane environment show --profile local-dev
      ;;
    venv)
      run "$VENV_PATH/bin/python" -m aiplane profiles list
      run "$VENV_PATH/bin/python" -c "import importlib.metadata as m; print(m.version(\"aiplane\"))"
      run "$VENV_PATH/bin/python" -m aiplane environment show --profile local-dev
      ;;
    conda)
      run conda run -n "$CONDA_ENV" python -m aiplane profiles list
      run conda run -n "$CONDA_ENV" python -c "import importlib.metadata as m; print(m.version(\"aiplane\"))"
      run conda run -n "$CONDA_ENV" python -m aiplane environment show --profile local-dev
      ;;
    docker)
      docker_run_aiplane profiles list
      docker_run_shell "python -c 'import importlib.metadata as m; print(m.version(\"aiplane\"))'"
      docker_run_aiplane environment show --profile local-dev
      ;;
  esac
}

activation_hint() {
  case "$MODE" in
    local)
      echo "Local mode uses the current shell environment; no activation command is needed."
      ;;
    venv)
      echo "To activate this environment in your current shell, run:"
      echo "  source scripts/activate_env.sh venv"
      ;;
    docker)
      echo "Docker image $DOCKER_IMAGE is ready. Run a CLI command with:"
      if [[ "$INSTALL_MODE" == "editable" ]]; then
        printf '  docker run --rm -v %q:/workspace -w /workspace %q sh -lc %q\n' "$PROJECT_ROOT" "$DOCKER_IMAGE" "python -m pip install -e . >/tmp/aiplane-install.log && python -m aiplane profiles list"
      else
        echo "  docker run --rm $DOCKER_IMAGE python -m aiplane profiles list"
      fi
      ;;
    conda)
      if [[ "$ACTIVATE_AFTER_INSTALL" -eq 0 ]]; then
        echo "Conda activation skipped because --activate 0 was supplied."
        echo "To activate later, run:"
        echo "  conda activate $CONDA_ENV"
        return 0
      fi
      if [[ "$DRY_RUN" -eq 1 ]]; then
        echo "+ conda activate $CONDA_ENV"
        return 0
      fi
      if [[ "${BASH_SOURCE[0]}" != "$0" ]]; then
        if ! command -v conda >/dev/null 2>&1; then
          echo "conda is not on PATH; cannot activate $CONDA_ENV" >&2
          return 1
        fi
        eval "$(conda shell.bash hook)"
        conda activate "$CONDA_ENV"
        echo "Activated Conda environment: $CONDA_ENV"
      else
        echo "Conda environment $CONDA_ENV is installed, but this script was executed, not sourced."
        echo "A child script cannot activate Conda in your parent shell. Practical options:"
        echo "  source scripts/setup_env.sh --mode conda --conda-env $CONDA_ENV --action install --install-mode $INSTALL_MODE"
        echo "  source .aiplane/activate-conda-$CONDA_ENV.sh"
        echo "  conda activate $CONDA_ENV"
        echo "Verify environments with:"
        echo "  conda env list"
      fi
      ;;
  esac
}

test_mode() {
  case "$MODE" in
    local)
      run_shell "PYTHONDONTWRITEBYTECODE=1 '$PYTHON_BIN' -m unittest discover -s tests"
      ;;
    venv)
      run_shell "PYTHONDONTWRITEBYTECODE=1 '$VENV_PATH/bin/python' -m unittest discover -s tests"
      ;;
    conda)
      run conda run -n "$CONDA_ENV" env PYTHONDONTWRITEBYTECODE=1 python -m unittest discover -s tests
      ;;
    docker)
      docker_run_shell "PYTHONDONTWRITEBYTECODE=1 PYTHONPATH=src python -m unittest discover -s tests"
      ;;
  esac
}

case "$ACTION" in
  install)
    echo "Install mode: $(install_label)"
    case "$MODE" in
      local) install_local ;;
      venv) install_venv ;;
      conda) install_conda ;;
      docker) install_docker ;;
    esac
    doctor_mode
    activation_hint
    ;;
  doctor)
    doctor_mode
    ;;
  test)
    test_mode
    ;;
esac
